export default images = {
  nav1: require('./../../assets/icon-21.png'),
  nav2: require('./../../assets/icon-22.png'),
  nav3: require('./../../assets/icon-23.png'),
  nav4: require('./../../assets/icon-24.png'),
  nav5: require('./../../assets/icon-25.png'),
  nav6: require('./../../assets/icon-26.png'),
  nav7: require('./../../assets/icon-27.png'),
  nav8: require('./../../assets/icon-28.png'),
  nav9: require('./../../assets/icon-29.png'),
  nav10: require('./../../assets/icon-30.png'),
  flag1: require('./../../assets/icon-en.png'),
  flag2: require('./../../assets/icon-pr.png'),
  facebook: require('./../../assets/icon-7.png'),
  google: require('./../../assets/icon-8.png'),
  backImage: require('./../../assets/icon-4.png'),
  back: require('./../../assets/icon-6.png'),
  share: require('./../../assets/share.png'),
  info: require('./../../assets/info.png'),
  yellow_info: require('./../../assets/yellow_info.png'),
  crosinf: require('./../../assets/crosinf.png'),
  moremenu: require('./../../assets/moremenu.png'),
  hamburger: require('./../../assets/hamburger.png'),
  correctIcon: require('./../../assets/correcticon.png'),
  rightgreen: require('./../../assets/rightgreen.png'),
  locationIcon: require('./../../assets/icon-18.png'),
  calenderIcon: require('./../../assets/icon-17.png'),
  clockIcon: require('./../../assets/icon-15.png'),
  dotIcon: require('./../../assets/icon-16.png'),
  thumbImage: require('./../../assets/icon-19.png'),
  thumbImage2: require('./../../assets/icon-12.png'),
  thumbImage3: require('./../../assets/icon-11.png'),
  thumbImage4: require('./../../assets/icon-52.png'),
  taskicon: require('./../../assets/icon-35.png'),
  page: require('./../../assets/icon-36.png'),
  banner: require('./../../assets/banner.png'),
  avatar: require('./../../assets/icon-10.png'),
  badge: require('./../../assets/icon-49.png'),
  badge2: require('./../../assets/icon-499.png'),
  backgroundprofile: require("../../assets/backgroundprofile.png"),
  upload: require('./../../assets/upload.png'),
  fileIcon: require('./../../assets/file.png'),
  upload1: require('./../../assets/upload1.png'),
  riyals: require('./../../assets/icon-38.png'),
  rupee: require('./../../assets/icon-38_2.png'),
  TomanEng: require('./../../assets/toman.png'),
  TomanPer: require('./../../assets/toman_par.png'),
  coverPic: require('./../../assets/icon-33.png'),
  dotwhite: require('./../../assets/dotwhite.png'),
  dotwhite2: require('./../../assets/dotwhitebig.png'),
  dotwhite3: require('./../../assets/dotwhitesmall.png'),
  filter: require('./../../assets/filter.png'),
  reversemenu: require('./../../assets/reversemenu.png'),
  payment_method: require('./../../assets/payment_method.png'),
  mobile: require('./../../assets/mobile.png'),
  star_review: require('./../../assets/star_review.png'),
  clip: require('./../../assets/clip.png'),
  reply: require('./../../assets/reply.png'),
  downarrow: require('./../../assets/downarrow.png'),
  send: require('./../../assets/send.png'),
  send_gray: require('./../../assets/gray_send.png'),
  attach: require('./../../assets/attach.png'),
  black_attach: require('./../../assets/black_attach.png'),
  calander: require("../../assets/calender2.png"),
  irantaskermapmarker: require("../../assets/map.png"),
  graymarker: require("../../assets/graylocation.png"),
  blackmarker: require("../../assets/blacklocation.png"),
  locationpin1: require("../../assets/pin1.png"),
  locationpin2: require("../../assets/pin2.png"),
  eye: require("../../assets/eye.png"),
  plus: require("../../assets/icon_plus.png"),
  cross: require("../../assets/cross-red.png"),
  crossWhite: require("../../assets/cross-w.png"),
  grayTick: require("../../assets/grayTick.png"),
  greenTick: require("../../assets/GreenTick.png"),
  rightArrow: require("../../assets/arrow_gray.png"),
  leftArrow: require("../../assets/arrow_gray2.png"),
  rightArrow2: require("../../assets/rightarrow2.png"),
  leftArrow2: require("../../assets/leftarrow.png"),
  leftArrow_white: require("../../assets/icon-53.png"),
  tickcircle: require("../../assets/tick-circle.png"),
  payping: require("../../assets/payping_icon.png"),
  bulb: require("../../assets/bulb.png"),
  binocular: require("../../assets/dur.png"),
  clock: require("../../assets/clock.png"),
  crosscircle: require("../../assets/cross.png"),
  arrowleftblack: require("../../assets/arrow-left-bloack.png"),
  arrowleftgrey: require("../../assets/arrow-left-grey.png"),
  arrowrightblaack: require("../../assets/arrow-right-bloack.png"),
  arrowrightgrey: require("../../assets/arrow-right-grey.png"),
  infoRed: require("../../assets/infored.png"),
  paymentSecure: require("../../assets/whiteGray.png"),
  bluePlus: require("../../assets/blue_plus-circle.png"),
  bag: require("../../assets/bag.png"),
  stargolden: require("../../assets/star.png"),
  stargray: require("../../assets/star1.png"),
  allgray: require("../../assets/star3.png"),
  onebyfour: require("../../assets/onebyfour.png"),
  fourbyone: require("../../assets/fourbyone.png"),
  zeroforth: require("../../assets/zeroforth.png"),
  onebyfourEn: require("../../assets/onefourthEn.png"),
  onebyfourPr: require("../../assets/onefourthPr.png"),
  twobyfourEn: require("../../assets/twofourthEn.png"),
  twobyfourPr: require("../../assets/twofourthPr.png"),
  threebyfourEn: require("../../assets/threefourthEn.png"),
  threebyfourPr: require("../../assets/threefourthPr.png"),
  greyarrowdown: require("../../assets/arrow-down-grey.png"),
  fb: require("../../assets/fb.png"),
  linkdin: require("../../assets/linkdin.png"),
  whatsapp: require("../../assets/whatsapp.png"),
  twiter: require("../../assets/twiter.png"),
  facebook_min: require("../../assets/facebook-min.png"),
  linkdin_min: require("../../assets/linkdin_min.png"),
  twiter_min: require("../../assets/twitter-min.png"),
  dollar: require("../../assets/dollar.png"),
  playbutton: require("../../assets/play2.png"),
  aboutusbanner: require("../../assets/aboutusbanner.jpg"),
  faq: require("../../assets/faq_ban.jpg"),
  aui: require("../../assets/aui.png"),
  wuser: require("../../assets/wuser.png"),
  wrench: require("../../assets/wrench.png"),
  thumbnail: require("../../assets/thumbnail.png"),
  howitworks: require("../../assets/howitworks.jpg"),
  hiw1: require("../../assets/hiw1.png"),
  hiw2: require("../../assets/hiw2.png"),
  hiw3: require("../../assets/hiw3.png"),
  cg: require("../../assets/community_img.png"),
  cg_tasker: require("../../assets/community_tasker_img.png"),
  cg_poster: require("../../assets/community_poster_img.png"),
  contactus: require("../../assets/contactus.jpg"),
  icon_logo: require("../../assets/icon_logo.png"),
  downlinearrow: require("../../assets/questionDown.png"),
  down_arrow: require("../../assets/down_arrow.png"),
  calen: require("../../assets/calen-popoup.png"),
  calenderr: require("../../assets/date.png"),
  grayPlus: require("../../assets/pls.png"),
  phone_p: require("../../assets/phone_p.png"),
  phone: require("../../assets/phone.png"),
  user: require("../../assets/user.png"),
  email: require("../../assets/email.png"),
  email_p: require("../../assets/email_p.png"),
  loc: require("../../assets/loc.png"),
  sub: require("../../assets/sub.png"),
  ir_icon: require("../../assets/ir_icon.png"),
  payments_earned: require("../../assets/payments_earned.webp"),
  debcr: require("../../assets/debcr-2.png"),
  debcard: require("../../assets/deb-card.png"),
  chat: require("../../assets/chat.png"),
  download: require("../../assets/download.png"),
  greyCross: require("../../assets/greyCross.png"),
  te: require("../../assets/te.png"),
  cp: require("../../assets/cp.png"),
  ts: require("../../assets/ts.png"),
  bl: require("../../assets/bl.png"),
  stage1: require("../../assets/stage1.png"),
  stage2: require("../../assets/stage2.png"),
  stage3: require("../../assets/stage3.png"),
  helpban: require("../../assets/helpban.jpg"),
  search: require("../../assets/icon-25.png"),
  info_black: require("../../assets/info_black.png"),
  pause: require("../../assets/pause.png"),
  resume: require("../../assets/resume.png"),
  delete: require("../../assets/delete.png"),
  edit: require("../../assets/edit.png"),
  lms_star: require("../../assets/ico4.png"),
  lms_pen: require("../../assets/ico3.png"),
  lms_arrow: require("../../assets/ico2.png"),
  lms_man: require("../../assets/ico5.png"),
  lms_info_g: require("../../assets/ico1.png"),
  aim: require("../../assets/aim.png"),
  baloon: require("../../assets/icon_new10.jpg"),
  rightarrow_blue: require("../../assets/rightarrow_blue.png"),
  leftarrow_blue: require("../../assets/leftarrow_blue.png"),
  health4: require("../../assets/health4.jpg"),
  health1: require("../../assets/health1.jpg"),
  post_img1: require("../../assets/post_img1.jpg"),
  img1: require("../../assets/icon_new12.jpg"),
  img2: require("../../assets/icon_new15.jpg"),
  img3: require("../../assets/icon_new16.jpg"),
  checked: require("../../assets/checkbox_full.png"),
  unchecked: require("../../assets/checkbox_empty.png"),

  round_checked: require("../../assets/round_full_check.png"),
  round_unchecked: require("../../assets/round_blank_check.png"),


  // irantaskerIcon:require("../../assets/icon-31.png"),
  irantaskerIcon: require("../../assets/irantasker_payping.png"),
  empty_my_task: require("../../assets/empty_my_task.png"),
  browserTask_notfound: require("../../assets/browserTask_notfound.png"),
  empty_message: require("../../assets/messageicon.png"),




  // ****************************new version***********************************
  splashScreen: require("../../assets/splashScreen.png"),
  splashScreen_image: require("../../assets/a_1.png"),
  splashScreen_image_white: require("../../assets/a_2.png"),
  eye_close: require("../../assets/eye_close.png"),
  eye_open: require("../../assets/eye_open.png"),
  resetPage_image: require("../../assets/aaaa_1.png"),
  resend: require("../../assets/ref1.png"),

  tabbar_getitdone: require("../../assets/check-circle.png"),
  tabbar_msg: require("../../assets/message-circle.png"),
  tabbar_task: require("../../assets/user_new.png"),
  tabbar_more: require("../../assets/more-horizontal.png"),
  white_star: require("../../assets/white_star.png"),
  double_arrow: require("../../assets/chevrons-right.png"),
  double_arrow_blue: require("../../assets/chevrons-right_blue.png"),
  double_arrow_new_blue: require("../../assets/chevrons-right_new_blue.png"),
  info_Red: require("../../assets/info-circle.png"),



  task_C: require("../../assets/task_C.png"),
  task_D: require("../../assets/task_D.png"),
  task_L: require("../../assets/task_L.png"),


  taskcard_C: require("../../assets/taskcard_C.png"),
  taskcard_L: require("../../assets/taskcard_L.png"),

  downlinearrow: require("../../assets/downlinearrow.png"),
  upload_image: require('./../../assets/upload_img.png'),
  green_round_tick: require('./../../assets/green_round_tick.png'),

  map_icon: require('./../../assets/map_icon.png'),



  white_search: require('./../../assets/white_search.png'),
  blue_search: require('./../../assets/blue_search.png'),
  dob_icon: require('./../../assets/dob_icon.png'),
  clock_new: require('./../../assets/clock_new.png'),
  reset_blue: require('./../../assets/reset_blue.png'),
  blue_plus_circle: require('./../../assets/blue_plus-circle.png'),
  plan_white_tick: require('./../../assets/plan_white_tick.png'),
  white_x: require('./../../assets/white_x.png'),
  new_edit: require('./../../assets/new_edit.png'),
  notification_bell: require('./../../assets/notification_bell.png'),
  appLogo_mapMarker: require('./../../assets/map.png'),

  menu_white: require('./../../assets/menu_white.png'),
  tick_white: require('./../../assets/tick_white.png'),


  logo_yellow: require('./../../assets/logo_yellow.png'),
  logo: require('./../../assets/logo.png'),
  startIntroSkipintro: require('./../../assets/Group7.png'),

  splash_1: require('./../../assets/splash_1.png'),
  splash_2: require('./../../assets/splash_2.png'),
  splash_3: require('./../../assets/splash_3.png'),

  AfterVideo: require('./../../assets/AfterVideo.png'),
  easypay_white: require('./../../assets/easypay_white.png'),
  signupbackground: require('./../../assets/signupbackground.png'),
  signupStyle: require('./../../assets/signupStyle.png'),
  phOtp: require('./../../assets/phOtp.png'),
  logo_secondary: require('./../../assets/logo_secondary.png'),
  logo_grey: require('./../../assets/logo_grey.png'),
  logo_primary: require('./../../assets/logo_primary.png'),
  logo_white: require('./../../assets/logo_white.png'),
  logo_white_name: require('./../../assets/logo_white_name.png'),



  white_tik: require('./../../assets/white_tik.png'),
  loderImage: require('./../../assets/loaderimage.png'),




  nricBack: require('./../../assets/nric-back.jpg'),
  nricFront: require('./../../assets/nric-front.jpg'),
  passportFront: require('./../../assets/passport-front.jpg'),




  loader: require('./../../assets/loader.png'),
  greycross_new: require('./../../assets/greyCross_new.png'),
  greyCheck: require('./../../assets/greyCheck.png'),


  // tabbar

  mytaskTabbarDisable: require("../../assets/tab_myTask_disable.png"),
  mytaskTabbarActive: require("../../assets/tab_myTask_active.png"),

  searchTabbarDisable: require("../../assets/tab_search_disable.png"),
  searchTabbarActive: require("../../assets/tab_search_active.png"),

  notificationTabbarDisable: require("../../assets/tab_notification_disable.png"),
  notificationTabbarActive: require("../../assets/tab_notification_active.png"),

  msgTabbarDisable: require("../../assets/tab_msg_disable.png"),
  msgTabbarActive: require("../../assets/tab_msg_active.png"),

  homeTabbarDisable: require("../../assets/tab_home_disable.png"),
  homeTabbarActive: require("../../assets/tab_home_active.png"),
  guidline: require("../../assets/guidline.png"),
  
  
  rejectacc: require("../../assets/rejectacc.png"),
  notverifyAcc: require("../../assets/notverifyAcc.png"),
  verifyacc: require("../../assets/verifyacc.png"),
  pendingacc: require("../../assets/pendingacc.png"),
  mapMarker: require("../../assets/map.png"),





};