export default {
  SELECTLANG: 'Select your preferred \nlanguage',
  SAVE: 'Save & Continue',
  CHANGELANG: 'Change Language',
  MORESCREEN: {
    HEADERTEXT: 'More Options',
    DASHBOARD: 'Fixer Dashboard',
    EDITPROFILE: 'My profile',
    SERVICES: 'List my services',
    LISTALLSERVICES: "List all services",
    LISTALLSERVICESHEADING: "List of Services",
    LISTALLSERVICESSUBHEADING: "Browse and reserve services in the list of recommended packages",
    PAYMENT: 'Payment History',
    BANKACCOUNT: 'Bank account details',
    REVIEWS: 'My reviews',
    TELLAFEIRND: 'Invite friends',
    NOTIFICATIONS: 'Notification',
    DISPUTES: 'Disputes',
    SETTINGS: 'Settings',
    HELPTOPICS: 'Help Topics',
    CHANGEPASS: 'Change Password',
    LOGOUT: 'Logout',
    FINANCE: 'My Wallet',
    CREATEDISPUTE: "Create Dispute",
    DISPUTEDETAILS: "Disputes Details",
    IRANTASKERADMIN: "EazyPay admin",
    DISCOVER: "Discover",
    INQUIRYVIAEMAIL: 'Inquiry via Email',
    REQUESTCALLBACK: 'Request a Callback',
  },
  SETTINGS: {
    HEADERTEXT: 'Settings',
    ACCOUNTS: 'Accounts',
    SKILLS: 'Skills',
    LISTMYSERVICES: 'List my services',
    BADGES: 'Badges',
    PORTFOLIO: 'Portfolio',
    PASSWORD: 'Password'
  },
  HELPTOPICS: {
    HEADERTEXT: 'Help Topics',
    ABOUTUS: 'About Us',
    CONTACTUS: 'Contact Us',
    HELP: 'Help Center',
    FAQ: 'FAQ',
    TANDC: 'Terms & Conditions',
    TANDC2: 'Terms & Services',
    PP: 'Privacy Policy',
    HIW: 'How It Works',
    BLOG: 'Blog',
    CG: 'Community Guidelines',
    CGP: 'Community Guidelines Poster',
    CGT: 'Community Guidelines Tasker',
    TASKERS: "Taskers",
    POSTERS: "Posters",
    BLOGDETAILS: 'Blog Details',
    EARNMONEY: 'Earn Money',
    SEEHOWITWORKS: 'See how it works',
  },

  TASKDETAILS: {
    HEADERTEXT: 'Task Details',
    POSTEDBY: "Posted by",
    CATEGORY: "Category",
    SUBCATAGORY: "SubCategory",
    SHOWMAP: "Show map",
    DUEDATE: "Due date",
    BUDGET: "Task Budget",
    TASKDESCRIPTION: "Task Description",
    QUESTION: "Questions",
    PROPOSAL: "Proposal",
    PLEASEDONTSHARE: "Please don't share personal info, doing so, may permanently ban your account.",
    REPLY: "Reply",
    SEND: "Send",
    MAKEANOFFER: "Make an offer",
    UPDATEOFFER: "Update Offer",
    CANCELLED: "Cancelled",
    PRIVATEMESSAGE: "Private Message",
    ASSIGNTASK: "Assign Task",
    TOTALOFFERSUBMITTED: "Total Offers",
    TOTALVIEWS: "Total Views",
    TASKSTATUS: "Task Status",
    INCREASEBYPOSTER: "Increase Payment By Poster",
    REQUESTBYTASKER: "(Requested by Tasker)",
    ASSIGNEE: "Assignee",
    INCREASEPRICE: "Increase payment",
    RELEASEREQUEST: "Request Release",
    RELEASE: "Release",
    TASKERREQUEST: "Tasker requested",
    AREYOUSURERELEASEPAYMENT: "Are you sure you want to release payment?",
    RISEDISPUTE: "Rise Dispute",
    VIEWDISPUTE: "View Dispute",
    RESCHEDULE: "Reschedule",
    RECHEDULEREQUEST: "Reschedule Request",
    WITHDRAW: "Withdraw",
    ADDSOMEINFOABOUTYOURTASK: "Add some info about your task",


    ASKAQUESTION: "Ask a question",
    TYPEYOURANS: "Type your answer here...",




    AWAITINGREPLY: "Awaiting reply",
    REVIEW: "Review",
    REVIEWED: "Reviewed",
    OTHEROPENJOBSBY: "Other open jobs by this Client",
    REVIEWOFFER: "Review offers",
    PAYMENTSECURE: "Payment Secure",
    YOUPAID: "You paid",
    TASKERWILLRECEIVE: "Tasker will receive",
    VIEWRESCHEDULEREQUEST: "View reschedule request",
    EDITREQUEST: "Edit request",
    REVIEWPROPOSEDDUEDATE: "Review Proposed Due Date",
    NEW: "NEW",
    REJECT: "Reject",
    ACCEPT: "Accept",
    ACCEPT2: "Accept",
    SENDRELEASEREQUEST: "Release request send successfully",
    DIDNOTLEAVEAREVIEW: "did not leave a review.",
    REVIEWREQUEST: "Review request",
  },
  MAKEANOFFER: {
    MAKINGMONEY: "To start making money",
    UPLOADAPROFILEPICTURE: "Upload a Profile Picture",
    PROFILEPHOTOSET: "Upload a Profile Picture",
    UPLOADPHOTO: "Upload photo",
    PROVIDEADDRESS: "Provide Address",
    ADDRESSADDED: "Address added",
    ENTERYOURADDRESS: "Enter your address",
    PROVIDEDOB: "Provide a Date of Birth",
    ENTERYOURDOB: "Enter your date of birth",
    VERIFYAMOBILENUMBER: "Verify a Mobile Number",
    VERIFYYOURPHONENUMBER: "Verify your phone number",
    VERIFYAEMAILADDRESS: "Verify an Email Address",
    VERIFYYOUREMAILADDRESS: "Verify your email Address",
    MAKEANOFFER: "Make an offer",
    TOSTARTMAKEINGMONEY: "To start making money",
    YOUROFFERAMOUNT: "Your Offer Amount",
    HOWDOTIERSANDFEESWORK: "How do tiers and fees work ?",
    HOWDOTIERSSUBTITLE: "There are four tiers - starting Bronze, advance to Silver, Gold, and ultimately Platinum. The higher the tier, the lower the service fee.",
    LEARNMORE: "Learn more",
    WHYAREYOUTHEBESTPERSON: "Why are you the best person for this task ?",
    WHYAREYOUTHEBESTSUBTITLE: "For your Safety. please do not share your personal information, e.g. email, phone number or address.",
    ENTERHERE: "Enter here...",
    DECLINEPLACEHOLDER: "I didn't accept the price increase because",
    ASKAQUESTIONABOUTATASK: "Ask a question about this task",
    SUBMITOFFER: "Submit Offer",
    ENTERAMOUNTTEXTINPUT: "Enter amount",
    UPDATEOFFER: "Update offer",
    PLEASEENTERGREATERTHAN2000: "Please enter a value greater than or equal to 2000",
    PLEASEENTERGREATERTHAN1000: "Please enter a value greater than or equal to 1000",
    MINIMUMBUDGET_GURUTASKER: "Total budget must be $5 or greater than $5",
    LESSTHAN500000000: "Please enter a value less than or equal to 1,00,000",
    ENTERDESCRIPTION: "Please enter description",
    MAKEANOFFERDONE: "Successfully make an offer done",
    LASTDIGIT0: "The last digit has to be 0",
    VALIDNUMBER: "Enter a valid number",
    ENTERAMOUNT: "Enter the amount",
    SUCCESSFULLYUPDATEOFFER: "Successfully update offer",
    OFFERCHAT: "Offer Chat",
    POSTER: "POSTER",
    ACCEPTOFFER: "Accept",
    SEND: "Send",
    TYPEYOURMSG: "Type your message here....",
    TYPEYOURMSG2: "Type your message here",
    PAYMENTREQUIRED: "Payment required",
    PAYMENTREQUIRED2: "Payment required",
    SUMMARY: "SUMMARY",
    SUMMARY2: "Summary",
    TASKPRICE: "Task Price",
    BOOKINGFEE: "Booking Fee",
    NEEDTOPAY: "Need to pay",
    ADJUSTFROMWALLET: "Adjust from wallet",
    PAYMENTMETHODS: "PAYMENT METHODS",
    PAYPING: "HitPay",
    PAYMENTWILLBE: "Payment will be secured inside",
    IRANTASKERPAY: "EazyPay Pay",
    UNTILLYOURE: "until you’re happy the task has been completed. View",
    TERMSANDCONDITIONS: "Terms & Conditions",
    SECURELYHOLDPAYMENT: "Securely hold payment",
    PAYMENT: "Payment",
    YOUOFFERED: "You offered",
    BRONZESERVICEFEE: "Bronze service fee",
    SERVICEFEE: "service fee",
    YOULLRECEIVE: "You'll receive",
    NEEDMOREDONE: "Need more done or task more complicated then your first thought? This is how you increase the task price.",
    HOWMUCHWOULD: "How much would you like to add?",
    TASKMORECOMPLICATED: "Task more complicated and bigger than the first agreed upon? Chat with your Job Poster then ask to increase the task price.",
    YOULLRECEIVEANEXTRA: "You'll recive an extra",
    ASKTOINCREASE: "Ask to increase",
    WAITINGFORINCREASE: "Waiting for Increase",
    PRICEINCREASEREQUESTED: "Price Increase Requested*",
    WALLET: "Wallet",
    APPROVE: "Approve",
    DECLINE: "Decline",
    THISWILLBESENT: "This will be sent as a private message to",
    DECLINEPRICEINCREASE: "Decline price increase",
    RESCHEDULETASK: "Reschedule Task",
    WHATISYOURDATE: "What is your preferred date?",
    ENTERAREASON: "Enter a reason for rescheduling (optional)",
    SUBMIT: "Submit",
    POSTREVIEWS: "Post Reviews",
    RATING: "Rating",
    YOURREVIEW: "Your Review",
    PLEASEPROVIDERATING: "Please provide ratings",
    ENTERYOURREVIEW: "Enter Your Review",
    REVIEWSEND: "Review send sucessfully",
    CLOSE: "Close",
    ITSAGREATWAY: "It's a great way to ensure your task is efficiently completed by discussing details such as time/date,address and contact information",
    SENDAPRIVATEMESSAGE: "Send a Private Message",
    GOTOTASK: "Go to task",
    YOUCANNOWSEND: "You can now send private messages with important imformation like the task location. Message your Tasker the details to get your task done!",
    ITSOFFICIAL: "It's Official"
  },
  MESSAGE: {
    HEADERTEXT: "Messages",
    ALLMESSAGES: 'All messages',
    UNREADMESSAGES: 'Unread messages',
    TYPEAMESSAGEHERE: "Type a message...",
    TYPING: "typing...",
    DISPUTETASK: "Dispute Task",

    EMPTYALLMSG: "You haven't got any messages yet - assign a task or get assigned to chat privately!",
    EMPTYUNREADMSG: "You haven't got any messages yet - assign a task or get assigned to chat privately!",
  },
  MYTASKSCREEN: {
    HEADERTEXT: 'My Tasks',

    POSTATASK: "Post a task",
    BROWSERTASK: "Browse tasks",
    CREATELISTING: "Create listing",
    LOOKSLIKEYOU: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",

    LOOKSLIKEYOU_ALL: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_POST: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_BOOKINGREQUEST: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_OFFERPENDING: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_OFFERACCEPT: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_CANCELTASK: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",
    LOOKSLIKEYOU_COMPLETEDTASK: "Looks like you haven't posted a task or made any offers yet. How about posting one now?",


    TASKS: 'Tasks',
    BOOKING: 'Booking',
    SELECTTASK: 'Select tasks',
    ALLTASK: 'All tasks',
    CANCELLEDTASK: 'Cancelled tasks',
    POSTEDTASK: 'Posted tasks',
    COMPLETEDTASK: 'Completed tasks',
    BOOKINGREQ: 'Booking request',
    OFFERPENDING: 'Offers pending',
    OFFERACCEPTED: 'Offers accepted',
    REMOTE: "Remote work",
    POSTEDON: "Posted on :"
  },
  BROWSE: {
    HEADERTEXT: 'Browse Tasks',
    NOTASK: "We couldn’t find any tasks that match - maybe try a different filter or search word?",
    BANNERHEADING: 'Earn more with listings',
    BANNERDESCRIPTION:
      'Create listings and well promote your services on EazyPay for free',
    LEARNMORETEXT: 'Learn More',
    REMOTE: "Remote work",
  },
  GETITDONE: {
    HEADTEXT: 'Get your to-do list done',
    TEXT: 'Get a top-rated Tasker in a just a few clicks with Instant Book',
    DESCTEXT: 'Tell us about your next home dean or removals task and get matched with a top-rated Tasker that can do the job',
    CARDTEXT: 'From',
    TASKOFFER: 'Describe what you need & get offers',
    RECEIVEANDREMOVE: 'Receive and remove offers from Tasker who can help',
    BOOKINGDESC: 'Popular Instant Booking',
    CLEANING: "Cleaning",
    FULLHOUSE: "Full House Removals",
    HANDYMAN: "Handyman",
    ASSAMBLY: "Assambly",
    DELIVERY: "Delivery",
    GARDENING: "Gardening",
    BUSSINESS: "Bussiness & Admin",
    EVENT: "Event & Photography",
    EVERYTHING: "Everything Else",
    POSTATASK: "Post a Task",
    TOPOSTINGATASK: "To posting a task and getting quotes",
    EXPLOREANDBOOK: "Explore and book all-new services, experiences and more",
    BROWSESERVICES: "Browse services in all categories",
    CANTFIND: "Can't find what you need?",
    CANTFIND2: "Can't find what you need?",
    POSTATASKANDGETOFFERS: "Post a task & get offers",
    POSTATASKANDGETOFFERS2: "Post a task & get offers"
  },
  POSTTASK: {
    NO: "No",
    YES: "Yes",
    HEADERTEXT: 'Post Task',
    HEADERTEXT2: 'Post Your Task',
    DETAILS: 'What you need done?',
    WHEN: 'Say where & when',
    IMAGE: 'Add Image',
    BUDGET: 'Budget',
    DESC: 'Tell us what you need done ?',
    CATAGORY: 'Choose a category',
    SUBCATAGORY: 'Choose a subcategory',
    CATEGORIES: "Categories",
    SUBCATEGORIES: "SubCategories",
    WHATDONE: 'What do you need done?',
    DETAIL: 'What are the details?',
    PLACETEXT1: 'e.g. Help move my sofa',
    PLACETEXT2: 'Describe your task in as much detail as possible.The more you describe what you need help with, the more accurate the offer will be.',
    ADDMUSTHAVES: "Add must-haves",
    MUSTHAVES: "Must-Haves",
    MUSTHAVESHEADING: "Add up to 3 things the Tasker needs to have or do to make an offer.",
    WHATMUST: "What must they have or do",
    ADD: "Add",
    SAVE: "Save",
    NEXT: 'Next',
    SUBMIT: 'Submit your task',
    WHENDONE: 'When do you need it done ?',
    ADDYOURTASKIMAGE: 'Add your task image',
    SUBTITLETASKIMAGE: 'The more images added that match your work / project, the better your chances of finding the right executors / contractors.',
    TIME: 'What time(s) do you need the Tasker',
    LOCATION: 'Location',
    ENTERYOURLOCATION: 'Enter your location',

    WHATISYOURBUDGET: 'What is your budget?',
    WHEREDOYOUNEED: 'Where do you need it done?',
    SUBTITLEYOURBUDGET: 'This is just an estimate. You can negotiate the final price later.',

    ONLINE: 'Online',
    INPERSON: 'In-person',
    TOTAL: 'Total',
    HOUR: 'Hourly rate',
    ENTER: 'Enter Here...',
    TBUDGET: 'Total budget',
    DESCRIPTION25CHAR: "Please enter atleast 25 characters description",
    ENTERDESCRIPTION: "Enter description",
    TITLE10CHAR: "Please enter atleast 10 characters title",
    ENTERTITLE: "Enter title",
    ENTERSUBCATAGORY: "Enter subcategory",
    ENTERCATAGORY: "Enter category",
    ATFIRSTENTER: 'At first enter something',
    PRESSADD: "Press Add button to save your task",
    SELECTDATE: "Select date",
    CHOOSEANYDATETYPE: "Choose any date type",
    SELECTLOCATION: "Select location",
    ENTEREACHFIELD: "Please enter each field",
    ENTER10Char: "Please enter at least 10 characters",
    ENTER25Char: " Please enter at least 25 characters",
    ENTERVALUE500000000: "Please enter budget less than or equal to 20000",
    ENTERVALUE500000000HOURLYRATE: "Please enter hourly rate less than or equal to 20000",
    ENTERVALUE100000000NUMOFHOUR: "Please enter number of hour less than or equal to 100000000",
    HRS: "Hrs",
    ONDATE: "On date",
    ON: "On",
    BEFOREDATE: "Before date",
    BEFORE: 'Before',
    IMFLEXIBLE: "I'm flexible",
    ENTERTIME: "Select time",
    SEARCH: "Search",
    OPTIONAL: "(optional)",
    ENTERIMAGEIN_JPEGPNGJPG: "The images must be a file of type: jpeg, png, jpg",
    NUMBEROFHOURS: "Number of hours",
    SUPPORTRDFIELS: "Supported files: .jpg,.jpeg,.png",
    MAXFILESIZE: "Max file size: 10Mb",
    ENTERVALUEMORETHAN1000: "Please enter budget more than or equal to 1000",
    ENTERVALUEMORETHAN1000HOURLYRATE: "Please enter hourly rate more than or equal to 1000",
    LASTDIGITMUSTBE0: "The last digit has to be 0",
    SELECTMUCHMORETIME: "Select much more time from current time",
    DONTSPACIALCHAR: "All Field must be enter a  integer. Don't use special characters and space",

    // *************************edittask********************

    EDITTASK: "Edit Task",
    SIMILARTASK: "Post similar task",
    EDIT: "Edit",
    CANCEL: "Cancel",
    POSTSIMILARTASK: "Post a similar task",
    REPORTHISTASK: "Report this task",
    READMORE: "Read More ＋",
    READLESS: "Read Less ―",
    MUSTHAVESTITLE: "Must haves",
    CANCELTASK: "Cancel Task",
    AREYOUSURE: "Are you sure?",
    CANCELABUTTON: "CANCEL",
    OK: "OK",
    DELETETASKIMAGE: "Task image deleted successfully"
  },
  BROWSEFILTER: {
    HEADERTEXT: "Filters",
    LOCATION: 'Location',
    LOCATIONPLACEHOLDER: 'Select location',
    DISTANCE: 'Distance',
    CATEGORY: 'Category',
    CATEGORYPLACEHOLDER: 'Select an item',
    SELECT: 'Select',
    TOBEDONE: 'To be done',
    INPERSON: 'In-Person',
    REMOTELY: 'Remotely',
    ALL: 'All',
    RANGE: 'Price',
    DATE: 'Date',
    DATEPLACEHOLDER: 'Choose date',
    APPLY: 'Apply',
    RESET: 'Reset',
    KM: 'KM',
    RIYALS: 'riyals',
    AND: '&',
    KEYWORDS: 'Keywords',
    SUBCATEGORY: "Subcategory",
    CHOOSECATEGORY: "Choose a category",
    SORTBY: "Sort by",
    BYDATE: "By date",
    PRICELOWTOHIGH: "Price low to high",
    PRICEHIGHTOLOW: "Price high to low",
    FROM: "From",
    TO: "To",
    ATFIRSTSELECTCATAGORY: "At first select category",
    TASKFOUND: "Tasks found",
    SELECTSUBCATEGORYALSO: "select subcategory also",
    EARN: "Earn",
    DUEDATE: "Due date :",
    POSTEDBY: "Posted by",
    VIEWTASK: "View Task",
    IRR: "IRR",
    TOMAN: "$",
    DRAFT: "Draft",
    OPEN: "Open",
    ASSIGNED: "Assigned",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    BUDGETRANGE: "Budget"
  },
  LOGINSCREEN: {
    HEADERTEXT: "Log In",
    EMAILPLACEHOLDER: 'Email/Phone Number',
    PASSWORDPLACEHOLDER: 'Password',
    FORGOTPASSBTN: 'Forgot password',
    LOGIN: 'Login',
    SEPERATOR: 'Login with account',
    FACEBOOK: 'Facebook',
    GOOGLE: 'Google',
    SIGNUPTEXT: "Don't have an account yet ?",
    SIGNUPBTN: 'Sign up',
    LOGOUT: "Logout Successfully",
  },
  FORGOTPASSBTN: {
    BACKTO: "Back To Login",
    RESETPASSWORD: "Reset Password",
    RESETPASSWORD2: "Reset Password",
    ENTERYOUREMAIL: "Enter your email below and we will send you instructions on how to reset your password",
  },
  SIGNUPCREEN: {
    HEADERTEXT: "Sign Up",
    NAMEPLAACEHOLDER: 'First name',
    LASTNAMEPLAACEHOLDER: 'Last name',
    EMAILPLACEHOLDER: 'Email address',
    PASSWORDPLACEHOLDER: 'Password',
    MOBILEPLACEHOLDER: 'Phone Number',
    CONFPASSPLACEHOLDER: 'Confirm password',
    FORGOTPASSBTN: 'Forgot password',
    SIGNUP: 'Sign up',
    SEPERATOR: 'or sign up with',
    FACEBOOK: 'Facebook',
    GOOGLE: 'Google',
    DESCTEXT: 'By signing up, I agree to EazyPay',
    AND: 'and',
    PRIVACY: 'Privacy Policy',
    TERMS: '\nTerms & Condition',
  },
  BASICINFO: {
    HEADERTEXT: 'Edit Profile',
    HEADING1: 'Basic Information',
    PLACEHOLDER: 'Enter here',
    ABOUTMEPLACEHOLDER: "Do not write contact info like Phone number, email etc. Otherwise your account will be locked.",
    FIRSTNAME: 'First name',
    LASTNAME: 'Last name',
    TAGLINE: 'Tag line (profile heading)',
    EMAIL: 'Email',
    PHONENUMBER: 'Phone number',
    HOURLYRATING: 'Hourly rate (as a tasker)',
    HIGHESTQUAL: 'Highest qualification',
    WORKEXP: "What's your work experience? (In Years)",
    LANGUAGEKNOWN: 'Languages known ?',
    SELECTLANGUAGE: 'Select Languages',
    TAXID: 'Tax ID',
    DOB: 'Date of birth',
    ROLEHEADING: 'On EazyPay I want to',
    POSTTASKS: 'Post tasks',
    EARNMONEY: 'Earn Money',
    VEICHLEHEADING: 'How do you get around?',
    BICYCLE: 'Bicycle',
    CAR: 'Car',
    ONLINE: 'Online',
    SCOOTER: 'Scooter',
    TRUCK: 'Truck',
    WALK: 'Walk',
    HEADING2: 'Address Information',
    COUNTRY: 'Nationality',
    STATE: 'State',
    CITY: 'City',
    LOCATION: "Location",
    ABOUTME: 'About me',
    PROFILEIMAGE: 'Upload profile image',
    BACKMAGE: 'Upload background image',
    SAVE: 'Save & Continue',
    VERIFIED: 'Verified',
    VERIFY: 'Verify',
    NOTIFICATION: "Notification",
    ON: "On",
    OFF: "Off"

  },
  PORTFOLIO: {
    HEADERTEXT: 'Portfolio image',
    HEADING: 'Portfolio images (optional)',
    PORTFOLIODELETE: 'Portfolio deleted successfully',
    DESC: 'Choose up to 15 images to showcase your portfolio \nsection',
    PREVIMAGES: 'Previously selected images',
    RECENTIMAGES: 'Recent selected images',
    BTNTEXT1: 'Recommended size 180px * 240px',
    BTNTEXT2: 'Supported files: .jpg, .jpeg, .png. Max file size: 10MB',
    SAVE: 'Save all changes',
  },
  SKILLS: {
    HEADERTEXT: 'Skills',
    INPUTHEADING: 'What are you good at ?',
    INPUTSUBHEADING: 'These are your skills. Keep them updated with any new skills you learn so other members can know what you can offer.',
    PLACEHOLDER: 'Enter here',
    ADDBTN: '+ Add',
    PREVSKILL: "Previously added skill",
    RECENTSKILL: "Recently added skill",
    ADDEDSKILLHEADING: 'Skills added by me',
    SKILLDELETE: "Skill deleted successfully",
    SAVE: 'Save & continue',
    ADDATLEASTONESKILL: 'Please add atleast one skill',
    ENTERSOMESKILL: 'Enter a skill',
    // SKILLPLACEHOLDER:"e.g. cleaning, driving and graphic design, etc",
    SKILLPLACEHOLDER: "Enter here...",

  },
  DASHBOARD: {
    TIER: "tier",
    HEADERTEXT: 'My Tasker Dashboard',
    CARDHEADING: 'Bronze tier',
    CARDTEXT1: '20% service fee excl GST',
    CARDTEXT1A: 'service fee',
    CARDTEXT2: 'Based on Completion Rating & Earning',
    SCOREHEADING: 'Your scores',
    COMPLETIONRATING: 'Your Completion Rating ',
    COMPLETIONDESC:
      'We have set your Completion Rating is Great to help kickstart your EazyPay journey. Complete your assigned task to keep this score high.',
    EARNING: 'Your Earnings',
    EARNINGDESC: '0 in the last 3-0 days',
    EARNINGDESC1: 'in the last',
    EARNINGDESC2: 'days',
    RIYALS: 'riyals',
    QUESTEXT: 'How do scores and tiers work ?',
    BENEFITHEADING: 'NEXT TIER BENEFITS',
    BENEFITTEXT1: 'Reach silver for lower service fees!',
    BENEFITTEXT2: 'Pay less with a service fee of 16.4%',
    BENEFITTEXT2A: 'Pay less with a service fee of',
    LAST: "Last",
    TASK: "tasks",
    DAYS: "days",
    POOR: "Poor",
    OKAY: "Okay",
    GOOD: "Good",
    EXCELLENT: "Excellent",
    TIERDETAILS: "Tier Details"
  },
  PAYMENTMETHOD: {
    HEADERTEXT: 'Payment Method'
  },
  MYREVIEW: {
    HEADERTEXT: 'My Review',
    ASATASKER: 'As a tasker',
    ASAPOSTER: 'As a poster'
  },
  PAYMENTHISTORY: {
    HEADERTEXT: 'Payment History',
    EARNED: 'Earned',
    OUTGOING: 'Outgoing',
    DOWNLOAD: "Download",
    CREDIT: "Credit",
    SHOW: "Show",
    ALL: "All",
    NETEARN: "Net Earned",
    DEBITED: "Debited",
    NETOUTGOING: "Net Outgoing",
    RAVI: "Ravindu",
    ASSIGNEDTO: "Assigned to",
    ASSIGNEDBY: "Assigned by",
    NEEDANILLUSTRATION: "Need an illustration to make an animation video",
    CHOOSEANYONE: "Choose any one",
    RANGE: "Range",
    ATFIRSTPOSTTASK: "At first post a task",

    OUTGOINGPAYMENT: "outgoing-payment-history_",
    EARNPAYMENT: "earned-payment-history_",
    DOWNLOADSUCCESSFULLY: "File Downloaded Successfully.",
    DOWNLOADING: "Downloading...",

    YOUHAVENTEARN: "You haven't earned from any tasks yet. Yet to find the right task?",
    YOUHAVENTPAID: "You haven't paid for any tasks yet. But let's change that!",
  },
  CHANGEPASS: {
    HEADERTEXT: 'Change Password',
    OLDPASSWORD: 'Old password',
    NEWPASSWORD: 'New password',
    CONFIRMNEWPASSWORD: 'Confirm password',
    CONFIRMNEWPASSWORD2: 'Confirm password',
    UPDATEPASSWORD: "Update password",
    ENTERHERE: "Enter here"
  },
  MYPROFILE: {
    TAB1: 'As a Tasker',
    TAB2: 'As a Poster',
    NOREVIEWTEXT: "No reviews received yet",
    ABOUT: 'About',
    MEMBERSINCE: 'Member since',
    BADGES: 'Badges',
    PORTFOLIO: 'Portfolio',
    SKILLS: 'Skills',
    NOSKILL: 'The user has not added any skills yet.',

    NOLISTING: "No listings",
    NOTRANSPOTATION: "No transportation means added",
    NOLANGUAGES: "No languages added",
    NOREVIEWSASAPOSTER: "This user has no reviews as a Poster yet",
    NOREVIEWSASATASKER: "This user has no reviews as a Tasker yet",
    // REVIEWS: 'Reviews',
    LANGUAGE: 'Language',
    GETAROUNDBY: "Transportation",
    ONLINE: "Online",
    LISTING: "Listings",
    NOREVIEWFOUND: "No review found",

    NOREVIEWFOUND2: "No reviews yet",


    COMPLETEDTASKS: "Completed tasks",
    STARS: "Stars",
    REVIEWS: "Reviews",
    FROM: "from"

  },
  ERROR: {
    REFRESHING: "Refreshing...",
    ENTERFNAME: "Enter first name",
    ENTERLNAME: "Enter last name",
    ENTERTAGLINE: "Enter Tag Line",
    ENTEREMAIL: "Enter email",
    ENTEREMAILORPHONE: "Enter email or phone number",
    ENTERVALIDEMAIL: "Plaese enter valid Email",
    ENTERPHONE: "Enter a Valid phone number",
    ENTERHOURLYRATE: "Enter Hourly rate",
    SELECTCOUNTRY: "Select Country",
    ENTERSTATENAME: "Enter state name",
    ENTERCITYNAME: "Select city name",
    SELECTLOCATION: "Select Location",
    ENTEREXPERIENCE: "Enter experience in number of year",
    ENTERHEIGHTESTQUALIFICATION: "Enter your highest qualification",
    ENTERDOB: "Enter Date of Birth",
    SELECTGETAROUND: "Select how do you get arround ",
    SELECTLANGUAGE: "Select languages",
    SOMETHINGERRORINAPI: "Something error in api call",
    AGEVALIDATION: "You must be 18 years or older to use EazyPay",
    EXPERIENCEPOSITIVEVALUE: "Enter experience in positive value",
    HOURLYRATEPOSITIVEVALUE: "Enter hourly rate in positive value",
    ENTERVALIDPHONE: "Enter valid phone number",
    ENTERPASSWORD8DIGIT: "Enter minimum 8 characters password",
    ENTERPASSWORD: "Please enter Password",
    CONFIRMPASSWORD: "Must be enter same password",
    SUCCESSFULLYLOGIN: "You are Successfully logged in",
    SUCCESSFULLYREGISTER: "You are Successfully registered",
    LOGINCANCEL: "Login cancelled",
    BOTHEMAIL_PHONE: "The email & phone both has already been taken",
    FILLUPALLFIELD: "Please fill Up All Fields",
    PASSWORDCHANGESUCCESSFULLY: "Password changed successfully",
    ENTERSAMEPASSWORD: "Enter same Password",
    ENTERYOUESKILL: "Enter your skill",
    ENTERADDBUTTON: "Enter add botton to add your skill",
    ENTERIMAGEIN_JPEGPNGJPG: "The portfolio images must be a file of type: jpeg, png, jpg",

    // make an offer
    SUCCESSFULLYTASKASSIGNED: "Sucessfully task assigned",
    PAYMENTCANCEL: "Payment Cancel",
    WAIT: "Wait",
    ATFIRSTENTERMSG: "At first enter message",
    ENTERMAX1000MSG: "Enter maximum 1000 characters message",
    MSGSEND: "Message send",
    PRICEINCREASESUCESSFULLY: "Price increase sucessfully",
    ENTERREASON: "Enter reason",
    ACCOUNTVERIFYING: "Account verifying......",
    ATFIRSTPHEMAILVERIFIED: "At first verified your phone number and email",
    PLEASESELECTADATE: "Please Select a date",
    YOUCANSENDWITHDRAW: "You can send withdrawal request after 2 days interval of your previos withdrawal request",
    YOUCANSENDWITHDRAW2: "You can send withdrawal request after 2 days interval of your previos withdrawal request",
    DAYSLEFT: "days left",
  },
  TABNAVIGATION: {
    GETITDONE: "Get it done",
    MYTASK: "My tasks",
    BROWSER: "Browse",
    MESSAGE: "Messages",
    MORE: "More",
    NOTIFICATIONS: 'Notification'
  },
  HELP: {
    HEADER: 'EazyPay Help Centre',
    SEARCHRESULT: "Search results",
    KNOWLEDGEBASE: "Knowledge base",
    SEARCH: "Search",
    NORESULTFOR: "No Results for",
    BROWSEKNOWLEDGEBASE: "Browse knowledge base",

  },
  DISPUTE: {
    ACTIVE: 'Active',
    CLOSED: 'Closed',
    NODISPUTE: 'No dispute found',
    FINALEVIDENCE: '(Final Evidence)',
    CLICKTOSELECTFILES: 'Click to select files',
  },
  LMS: {
    HEADER: "Create your listing",
    CATEGORY: "Category",
    DESCRIPTION: "Description",
    PRICINGANDPACKAGING: "Pricing & packaging",
    LOCATION: "Location",
    AVAILABILITY: "Availability",
    IMAGES: "Images",
    BOOKINGMESSAGE: "Booking Message",
    ONLINESERVICE: "Online Service",
    LMS1_TEXT_1: "What type of service will this listing offer?",
    LMS1_TEXT_2: "Choose a category that best describes the service being offered in this listing. This will help customers find and book your listing.",
    LMS1_TOAST_1: " Select category",
    LMS1_TOAST_2: " Select subcategory",
    CHOOSECATEGORYTITLE: "Choose a main category",
    CHOOSECATEGORYPLACEHOLDER: "Choose a main category",
    CHOOSESUBCATEGORYTITLE: "Choose a subcategory",
    CHOOSESUBCATEGORYPLACEHOLDER: "Choose a subcategory",
    LMS2_TEXT_1: "Describe your listing",
    LMS2_TEXT_2: "This is your chance to impress potential customers with what this listing offers and why you are the best person for the job.",
    LMS2_TEXT_3: "Title",
    LMS2_TEXT_4: "Write a short title that accurately describes the service you will provide.",
    LMS2_TEXT_5: "e.g. Family and Newborn Photography",
    LMS2_TEXT_6: "Search tags",
    LMS2_TEXT_7: "Type and enter up to 15 search terms customers might use when searching for your listing.",
    LMS2_TEXT_8: "e.g. photography,photoshoot,family,baby",
    LMS2_TEXT_9: "Edit",
    LMS2_TEXT_10: "Description",
    LMS2_TEXT_11: "Please describe the service you are offering in detail",
    LMS2_TEXT_12: "Enter your description here...",
    LMS2_TEXT_13: "Please note",
    LMS2_TEXT_14: "Do not put prices in your listing description. You can set up price packages for your listing in the next step.",
    SEARCHTAGCANNOTBE15: "Search tags cannot be greater than 15",
    ATLEAST50CHAR: "Please enter at least 50 characters Description",
    ATLEAST1TAG: "Please provide at least 1 tag(s)",
    PLEASEENTERTITLE: "Please enter Title",
    ENTERATAG: "Enter a search tag",
    TAGDELETED: "Search tag deleted successfully",

    PRICEANDPACKAGEYOURLISTING: "Price & package your listing",
    PRICEYOURLISTINGWITH: "Price your listing with a single price or up to 5 price packages.",
    PACKAGE1: "Package 1",
    PACKAGE22: "Package 2",
    PACKAGE3: "Package 3",
    PACKAGE4: "Package 4",
    PACKAGE5: "Package 5",
    OPTIONAL: "(Optional)",
    CUSTOMERWILLSELECT: "Customers will select 1 package when requesting to book your listing.",
    ADD: "Add",
    PACKAGENAME: "Package name",
    DESCRIBETHISPACKAGE: "Describe this package",
    LISTEVERYTHING: "List everything that this package includes",
    ENTERHERE: "Enter here...",
    TOTALPRICE: "Total price",
    BELOWTOTALPRICE_TEXT: "EazyPay will deduct a service fee between 10-20% of the package price depending on your tier at time of booking.",
    PLEASEADD5CHARNAME: "Please add at least 5 characters package name",
    PLEASEADD25CHARDESCRIPTION: "Please add at least 25 characters package description",
    PLEASEENTERAMOUNT1000TOMAN: "Please enter amount at least 1000 Toman , upto 50,000,000 Toman",
    PLEASEENTERALLVALUEIN2: "Please enter all values in package 2",
    PLEASEENTERALLVALUEIN3: "Please enter all values in package 3",
    PLEASEENTERALLVALUEIN4: "Please enter all values in package 4",
    PLEASEENTERALLVALUEIN5: "Please enter all values in package 5",
    PLEASEADDATLEAST1PACKAGE: "Please add at least 1 price package",

    CHOOSEWHEREYOUWILL: "Choose where you will deliver this service",
    ONLINE: "Online",
    THISSERVICEANYWHERE: "This service has to be delivered from anywhere",
    INPERSON: "In-person",
    THISSERVICEINPERSON: "This service has to be delivered in-person",
    IWILLSERVE: "I will serve customers within",
    KM: "km",
    FROMMYLOCATION: "From my location",
    SELECT: "Select...",
    SELECTLOCATION: "Please selete location",

    SETAVAILABILITY: "Set your availability",
    LETCUSTOMERSKNOW: "Let customers know what your schedule looks like and when you are available to provide this service.",
    MYAVAILABILITY: "My Availability",
    IAMAVAILABLEON: "I am available on...",
    CUSTOMERWILLREQUESTTOBOOK: "Customers will request to book your listing. You will be notified of new booking requests and given the opportunity to confirm or reject the booking.",
    YOUCANASK: "You can ask questions and discuss requirements with the customer before making this decision.",
    ENTER20CHAR: "Please enter at least 20 characters",

    ADDIMAGES: 'Add images',
    ADDHIGHQUALITYIMAGES: "Add high quality images that visually describe this listing.",
    MAINIMAGE: "Main image",
    THISISFIRSTIMAGE: "This is the first image potential customers see when viewing your listing",
    GALLARYIMAGES: "Gallery Images",
    CHOOSEUPTO15: "Choose up to 15 images to showcase your work and skill",
    MAINIMAGEMUST: "Main image must be select",
    CHOOSEUPTO15IMAGES: "Choose up to 15 gallary images",

    AUTOSENDAMESSAGE: "Auto-send a message to new customers",
    WRITEAMESSAGETOBE: "Write a message to be automatically sent to customers when they request to book your listing.",
    WRITEAMESSAGE: "Write a message",
    THANKSFORBOOKINGMYLISTING: "Thanks for booking my listing! I will need a fwe things from you to get started...",
    POSTYOURLISTING: "Post your listing ",
    MYSERVICES: "My services",
    CREATENEWLISTING: "Create new listing",
    PUBLISHED: "PUBLISHED",
    PAUSED: "PAUSED",
    NEXTSTEPS: "NEXT STEPS",
    BOOKINGFORYOUR: `Bookings for your listings will appear as "Booking request" in`,
    MYTASK: "My Task",
    ABOUTLISTINGOR: "about listings or visit our",
    HELPCENTER: "Help Center",
    HELPCENTER_2: "Help Center",
    LISTINGDETAILS: "Listing Details",
    STARTINGFROM: "Starting from :",
    ABOUTTHISTASKER: "About this Tasker",
    VIEWALLPACKAGE: "View all packages",
    PRICEPACKAGES: "Price Packages",
    COST: "Cost :",
    CONTINUETOBOOK: "Continue to book",
    REVIEWFORTHISTASKER: "Reviews for this tasker",
    HASNOTRECIVEDANYREVIEW: "hasn't received any reviews just yet.",



    REQUESTBOOKING: "Request booking",
    PLEASEFILLINTHE: "Please fill in the below fields to continue booking",
    PACKAGE: "Package :",
    PACKAGE2: "Package :",
    WHEREDOYOU: "Where do you need this done?",
    WHENDOYOU: "When do you need it done?",
    TIMEOPTIONAL: "Time (optional)",
    WHATTIMESDO: "What time(s) do you need the Tasker?",
    PRIVATEMSG: "Private message (optional)",
    INTRODUCEYOURSELF: "Introduce yourself, add extra details or ask a question.",
    ENTERYOURMESSAGE: "Enter your message here.....",
    SENDBOOKING: "Send booking request",
    VIEWBOOKINGREQUEST: "View booking request",
    WHATHAPPENS: "What happens next?",
    CREATELISTING: "Create Listing",
    WORKLESSEARNMORE: "Work less. Earn more",
    BEONEOFTHE: "Be one of the first to turn your service into a listing and we will promote your services to over 4 million customers. For free.",
    CREATEMYFIRST: "Create my first listing",
    BELLOWFSTBUTTON: "Lorem ipsum dolor sit amet, consectetur adipiscing sed do eiusmod tempor incididunt labore dolore is magna aliqua enim lorem ipsum sectetur",
    CREATEYOURFIRST: "Create your first listing",
    YOUCANEARN: "You can earn from any skill",
    THEREISNOLIMIT: "There is no limit to the quirky and unique listings you can create",
    WEAREHERETOHELP: "We are here to help",
  },
  TELLAFEIRND: {
    FRIENDNAME: "Friend name",
    FRIENDEMAIL: "Friend email",
    ENTERYOURFRIENDNAME: "Enter your friend name",
    ENTERYOURFRIENDEMAIL: "Enter your friend email",
    MESSAGE: "Message",
    PLEASEWRITEACOMMON: "Please write a common message for your all friends.",
    ENTERYOURMESSAGEHERE: "Enter your message here...",
    FRIEND: "Friend",
    NAME: "Name :",
    EMAIL: "Email :",
    ENTERMESSAGE: "Enter message",
    ENTERATLEAST1FRIEND: "Enter at least 1 friend",
    ENTERADDBUTTON: "At first enter add button to save name and email",
    ENTERNAME: "Enter name"

  },
  NOTIFICATIONS: {
    HEADER: "Notifications"
  },
  WITHDRAW: {
    NORECORDFOUND: "No record found"
  },
};
