export default {
  SELECTLANG: 'زبان مورد نظر خود را انتخاب کنید',
  SAVE: 'ذخیره و ادامه دهید',
  CHANGELANG: 'تغییر زبان',
  MORESCREEN: {
    HEADERTEXT: 'گزینه های بیشتر',
    DASHBOARD: 'رتبه من',
    EDITPROFILE: 'ویرایش پروفایل',
    SERVICES: 'بسته های پیشنهادی من',
    LISTALLSERVICES: "بسته های پیشنهادی",
    LISTALLSERVICESHEADING: "ترجیح می دهید خودتان یک مجری / پیمانکار را انتخاب کنید ؟",
    LISTALLSERVICESSUBHEADING: "جستجو در استخر بسته های پیشنهادی و رزرو خدمات",
    PAYMENT: 'تاریخچه پرداخت',
    BANKACCOUNT: 'مشخصات حساب بانکی',
    REVIEWS: 'نظرات / دیدگا‌ه های  من',
    TELLAFEIRND: 'به دوستت بگو',
    NOTIFICATIONS: 'اعلان ها',
    DISPUTES: 'اختلافات',
    SETTINGS: 'تنظیمات',
    HELPTOPICS: 'راهنما',
    CHANGEPASS: 'تغییر رمز عبور',
    LOGOUT: 'خروج',
    FINANCE: 'کیف پول',
    CREATEDISPUTE: "ایجاد اختلاف",
    DISPUTEDETAILS: "جزئیات اختلاف",
    IRANTASKERADMIN: "EazyPay admin",
    DISCOVER: "بیشتر بدانید",
    INQUIRYVIAEMAIL: 'Inquiry via Email',
    REQUESTCALLBACK: 'Request a Callback',
  },

  SETTINGS: {
    HEADERTEXT: 'تنظیمات',
    ACCOUNTS: 'حساب کاربری',
    SKILLS: 'مهارت ها',
    LISTMYSERVICES: 'خدمات من را لیست کنید',
    BADGES: 'نشان ها',
    PORTFOLIO: 'نمونه کارها',
    PASSWORD: 'کلمه عبور'
  },
  HELPTOPICS: {
    HEADERTEXT: 'راهنما',
    ABOUTUS: 'درباره ما',
    CONTACTUS: 'تماس با ما',
    HELP: 'راهنما',
    FAQ: 'سوالات متداول',
    TANDC: 'شرایط و ضوابط',
    TANDC2: 'شرایط و خدمات',
    PP: 'حریم خصوصی',
    HIW: 'چگونه کار می کند',
    BLOG: 'وبلاگ',
    CG: 'دستورالعمل های انجمن',
    CGP: "پوستر دستورالعمل های انجمن",
    CGT: 'Tasker دستورالعمل های انجمن',
    TASKERS: "مجریان/پیمانکاران",
    POSTERS: "کارفرمایان",
    BLOGDETAILS: 'جزئیات وبلاگ',
    EARNMONEY: 'کسب درآمد',
    SEEHOWITWORKS: 'ببینید چگونه کار می کند',
  },
  MYREVIEW: {
    HEADERTEXT: 'نظرات و دیدگاه های ارسال شده توسط من',
    ASATASKER: 'مجری/پیمانکار',
    ASAPOSTER: 'کارفرما'
  },
  PAYMENTHISTORY: {
    HEADERTEXT: 'سابقه پرداخت',
    EARNED: 'ورودی',
    OUTGOING: 'خروجی',
    DOWNLOAD: "دانلود",
    CREDIT: "مبلغ",
    SHOW: "در حال نمایش",
    ALL: "همه",
    NETEARN: "مجموع ورودی",
    DEBITED: "مبلغ",
    NETOUTGOING: "مجموع خروجی",
    RAVI: "راویندو",
    ASSIGNEDTO: "محول شده به",
    ASSIGNEDBY: "محول شده توسط",
    NEEDANILLUSTRATION: "برای ساخت یک فیلم متحرک به تصویر نیاز دارید",
    CHOOSEANYONE: "هر کسی را انتخاب کنید",
    RANGE: "بازه زمانی",
    ATFIRSTPOSTTASK: "ابتدا یک کار ارسال کنید",

    OUTGOINGPAYMENT: "سابقه-پرداخت-خروجی_",
    EARNPAYMENT: "سابقه-پرداخت-به دست آمده_",
    DOWNLOADSUCCESSFULLY: "فایل با موفقیت دانلود شد",
    DOWNLOADING: "در حال دانلود...",

    YOUHAVENTEARN: "هیچ رسید دریافت و پرداختی یافت نشد. با کلیک بر روی دکمه زیر به استخر کارها وارد شوید…",
    YOUHAVENTPAID: "هنوز برای هیچ کار/پروژه ای پولی پرداخت نکرده اید.",
  },
  TASKDETAILS: {
    HEADERTEXT: 'جزئیات وظیفه',
    POSTEDBY: "ارسال شده توسط",
    CATEGORY: "دسته بندی",
    SUBCATAGORY: "زیرمجموعه",
    SHOWMAP: "نشان دادن نقشه",
    DUEDATE: "تاریخ سررسید",
    BUDGET: "مبلغ پروژه",
    TASKDESCRIPTION: "شرح کار/ پروژه",
    QUESTION: "سوالات",
    PROPOSAL: "پیشنهادات",
    PLEASEDONTSHARE: "لطفا اطلاعات تماس خود را به اشتراک نگذارید، در صورت مشاهده، پروفایل کاربر مورد نظر بلاک شده و کاربر مورد نظر هرگونه حق قانونی را از خود سلب خواهد کرد. همچنین توجه داشته باشید ایران تسکر هیچ گونه مسئولیتی برای معاملاتی که خارج ازقوانین جمهوری اسلامی ایران انجام میشود قائل نیست، و در صورت مشاهده کار/پروژه مورد نظر حذف و کاربر مورد نظر بلاک خواهد شد. همچنین ایران تسکر حق طبیعی خود میداند که در صورت مشاهده موارد خلاف شرع و عرف مراتب را به مراجع قضائی اطلاع دهد.",
    REPLY: "پاسخ",
    SEND: "ارسال",
    MAKEANOFFER: "ارائه پیشنهاد",
    UPDATEOFFER: "بروز رسانی پیشنهاد",
    CANCELLED: "لغو شد",
    PRIVATEMESSAGE: "پیام خصوصی",
    ASSIGNTASK: "تعیین تکلیف",
    TOTALOFFERSUBMITTED: "تعداد پیشنهادات ارسالی",
    TOTALVIEWS: "تعداد بازدیدها",
    TASKSTATUS: "وضعیت کار/پروژه",
    INCREASEBYPOSTER: "افزایش قیمت های اعمال شده توسط کارفرما:",
    REQUESTBYTASKER: "(درخواست شده توسط مجری)",
    ASSIGNEE: "محول شده",
    INCREASEPRICE: " افزایش قیمت",
    RELEASEREQUEST: "درخواست آزاد سازی",
    RELEASE: "آزاد سازی",
    // TASKERREQUEST:"مجری کار/ پروژه درخواست آزادسازی مبلغ را ارسال کرده است",
    TASKERREQUEST: "بررسی درخواست",
    AREYOUSURERELEASEPAYMENT: "آیا مطمئن هستید که می خواهید آزاد سازی را اعمال کنید؟",
    RISEDISPUTE: "ایجاد اختلاف",
    VIEWDISPUTE: "مشاهده اختلاف",
    RESCHEDULE: "زمانبندی دوباره",
    RECHEDULEREQUEST: "درخواست زمان بندی جدید",
    WITHDRAW: "لغو پیشنهاد",
    ADDSOMEINFOABOUTYOURTASK: "اطلاعاتی در مورد وظیفه خود اضافه کنید",


    ASKAQUESTION: "سؤالی دارید؟",
    TYPEYOURANS: "پاسخ خود را اینجا بنویسید ...",



    AWAITINGREPLY: "در انتظار پاسخ",
    REVIEW: "نظر/دیدگاه",
    // REVIEWED: "بررسی شده",
    REVIEWED: "نظر/دیدگاه اعمال شد",
    OTHEROPENJOBSBY: "کار/پروژه های باز توسط این کاربر",
    REVIEWOFFER: "مرور پیشنهادات",
    PAYMENTSECURE: "پرداخت امن",
    YOUPAID: "پرداختی شما",
    TASKERWILLRECEIVE: "Tasker دریافت خواهد کرد",
    VIEWRESCHEDULEREQUEST: "مشاهده درخواست زمان‌بندی جدید",
    EDITREQUEST: "ویرایش",
    REVIEWPROPOSEDDUEDATE: "زمانبندی پیشنهادی",
    NEW: "جدید",
    REJECT: "رد کردن",
    ACCEPT: "تایید کنید",
    ACCEPT2: "قبول",
    SENDRELEASEREQUEST: "درخواست انتشار با موفقیت ارسال شد",
    DIDNOTLEAVEAREVIEW: "نظر و دیدگاهی گذاشته نشده است",
    REVIEWREQUEST: "پیام خصوصی",
  },
  MAKEANOFFER: {
    MINIMUMBUDGET_GURUTASKER: "Total budget must be $5 or greater than $5",
    MAKINGMONEY: "آیا اماده کسب درآمد هستید ؟؟؟",
    UPLOADAPROFILEPICTURE: "بارگذاری عکس پروفایل",
    PROFILEPHOTOSET: "عکس پروفایل اضافه شد",
    UPLOADPHOTO: "بارگذاری عکس",
    PROVIDEADDRESS: "آدرس",
    ADDRESSADDED: "آدرس",
    ENTERYOURADDRESS: "آدرس خود را وارد کنید",
    PROVIDEDOB: "تاریخ تولد",
    ENTERYOURDOB: "تاریخ تولد خود را وارد کنید",
    VERIFYAMOBILENUMBER: "شماره همراه",
    VERIFYYOURPHONENUMBER: "شماره همراه خود را تایید کنید",
    VERIFYAEMAILADDRESS: "آدرس ایمیل",
    VERIFYYOUREMAILADDRESS: "آدرس ایمیل خود را تایید کنید",
    MAKEANOFFER: "ارسال پیشنهاد",
    TOSTARTMAKEINGMONEY: "آیا اماده کسب درآمد هستید ؟؟؟",
    YOUROFFERAMOUNT: "پیشنهاد شما",
    HOWDOTIERSANDFEESWORK: "طبقات و هزینه خدمات چگونه کار می کنند",
    HOWDOTIERSSUBTITLE: "چهار سطح وجود دارد - شروع برنز، پیشرفت به نقره، طلا، و در نهایت پلاتین. هر چه ردیف بالاتر باشد، هزینه خدمات کمتر است.",
    LEARNMORE: "اطلاعات بیشتر",
    WHYAREYOUTHEBESTPERSON: "چرا شما بهترین فرد برای این کار هستید؟",
    WHYAREYOUTHEBESTSUBTITLE: "برای امنیت تو. لطفا اطلاعات شخصی خود را به اشتراک نگذارید، به عنوان مثال ایمیل، شماره تلفن یا آدرس.",
    ENTERHERE: "اینجا وارد کنید...",
    DECLINEPLACEHOLDER: "درخواست افزایش قیمت مورد تایید نیست، زیرا",
    ASKAQUESTIONABOUTATASK: "در مورد این کار/ پروژه سوالی دارید؟",
    SUBMITOFFER: "ارسال پیشنهاد",
    ENTERAMOUNTTEXTINPUT: "مقدار را وارد کنید",
    UPDATEOFFER: "به روز رسانی پیشنهاد",
    PLEASEENTERGREATERTHAN2000: "لطفاً مقداری بزرگتر یا مساوی ۲۰۰۰ وارد کنید",
    // PLEASEENTERGREATERTHAN1000: "لطفاً مقداری بزرگتر یا مساوی ۱۰۰۰ وارد کنید",
    PLEASEENTERGREATERTHAN1000: "لطفاً مقداری بزرگتر یا مساوی وارد کنید ۱۰۰۰.",
    LESSTHAN500000000: "لطفاً مقداری کمتر یا مساوی وارد کنید ۵۰,۰۰۰,۰۰۰.",
    ENTERDESCRIPTION: "لطفا توضیحات را وارد کنید",
    MAKEANOFFERDONE: "با موفقیت یک پیشنهاد انجام شد",
    LASTDIGIT0: "آخرین رقم باید ۰ باشد",
    VALIDNUMBER: "یک عدد معتبر وارد کنید",
    ENTERAMOUNT: "مقدار را وارد کنید",
    SUCCESSFULLYUPDATEOFFER: "پیشنهاد با موفقیت به‌روزرسانی شد",
    OFFERCHAT: "مرور پیشنهادات",
    POSTER: "کارفرما",
    ACCEPTOFFER: "تایید",
    SEND: "ارسال",
    TYPEYOURMSG: "پیام خود را اینجا تایپ کنید ....",
    TYPEYOURMSG2: "پیام خود را اینجا تایپ کنید",
    PAYMENTREQUIRED: "مستلزم پرداخت",
    PAYMENTREQUIRED2: "در انتظار پرداخت",
    SUMMARY: "خلاصه",
    SUMMARY2: "شرح پرداخت",
    TASKPRICE: "قیمت کار/پروژه",
    BOOKINGFEE: "هزینه رزرو خدمات",
    NEEDTOPAY: "نیاز به پرداخت",
    ADJUSTFROMWALLET: "پرداخت بوسیله کیف پول",
    PAYMENTMETHODS: "روش های پرداخت",
    PAYPING: "ایران تسکر",
    PAYMENTWILLBE: "پرداخت های شما در ایران تسکر به صورت",
    IRANTASKERPAY: "امن و گرو گذاری",
    UNTILLYOURE: "شده انجام خواهد شد. به این صورت که مبلغ پرداختی شما  به صورت امانت نزد ایران تسکر نگهداری می شود و تنها زمانی پول به حساب مجری/پیمانکار مربوطه واریز خواهد شد که شما رضایت خود از نحوه انجام کار را با فشردن کلید (آزادسازی مبلغ پروژه) اعلام کرده باشید.",
    TERMSANDCONDITIONS: "شرایط و ضوابط",
    SECURELYHOLDPAYMENT: "پرداخت امن با ایران تسکر",
    PAYMENT: "پرداخت",
    YOUOFFERED: "پیشنهاد شما",
    BRONZESERVICEFEE: "هزینه خدمات برنز",
    SERVICEFEE: "هزینه خدمات",
    YOULLRECEIVE: "دریافتی شما",
    NEEDMOREDONE: "اگر فکر می کنید به هر دلیلی نیاز به افزایش مبلغ کار/ پروژه دارید، صرفا مبلغی که می خواهید به مبلغ پروژه اضافه شود را در کادر زیر وارد نمایید.",
    HOWMUCHWOULD: "مبلغ مورد نظر که می خواهید اضافه کنید چقدر است ؟",
    TASKMORECOMPLICATED: "کار پیچیده تر و بزرگتر از آن چیزی است که در ابتدا مورد توافق واقع شده است؟ می توانید مجددا با کارفرمای خود مذاکره کنید و از او بخواهید که قیمت کار را افزایش دهد.",
    YOULLRECEIVEANEXTRA: "شما یک اضافی دریافت خواهید کرد",
    ASKTOINCREASE: "افزایش مبلغ",
    WAITINGFORINCREASE: "در انتظار تایید",
    PRICEINCREASEREQUESTED: "درخواست افزایش قیمت*",
    WALLET: "کیف پول",
    APPROVE: "تایید",
    DECLINE: "رد",
    THISWILLBESENT: "This will be sent as a private message to",
    DECLINEPRICEINCREASE: "رد درخواست و ارسال پیام",
    RESCHEDULETASK: "زمانبندی مجدد کار/پروژه",
    WHATISYOURDATE: "تاریخ جدید مورد نظر شما چیست؟",
    ENTERAREASON: "دلیلی برای تغییر در زمانبندی وارد کنید",
    SUBMIT: "ارسال",
    POSTREVIEWS: "ارسال دیدگاه",
    RATING: "رتبه بندی",
    YOURREVIEW: "نظر و‌دیدگاه شما",
    PLEASEPROVIDERATING: "لطفا رتبه بندی را ارائه دهید",
    ENTERYOURREVIEW: "نظر خود را وارد کنید",
    REVIEWSEND: "بررسی ارسال با موفقیت",
    CLOSE: "نزدیک",
    ITSAGREATWAY: "یک راه عالی برای اطمینان از این که کار/ پروژه به شکل موثر محول شده است بحث در مورد جزئیاتی مانند زمان/تاریخ،مبلغ، آدرس و اطلاعات تماس است.",
    SENDAPRIVATEMESSAGE: "ارسال پیام خصوصی",
    GOTOTASK: "به کار/ پروژه بروید",
    YOUCANNOWSEND: "اکنون می توانید با ارسال پیام خصوصی به مجری مربوطه  و ارسال اطلاعات تماس ، کار/ پروژه خود را شروع کنید. موفق باشید!",
    ITSOFFICIAL: "پرداخت امن"
  },
  MESSAGE: {
    HEADERTEXT: "پیام",
    ALLMESSAGES: 'همه پیام ها',
    UNREADMESSAGES: 'پیام های خوانده نشده',
    TYPEAMESSAGEHERE: "یک پیام تایپ کنید...",
    TYPING: "تایپ کردن...",
    DISPUTETASK: "وظیفه اختلاف",

    EMPTYALLMSG: "هنوز هیچ پیامی دریافت نکرده اید.",
    EMPTYUNREADMSG: "هیچ پیام خوانده نشده ای وجود ندارد.",
  },
  MYTASKSCREEN: {
    HEADERTEXT: 'کارها/پروژه های من',


    POSTATASK: "ایجاد یک کار/پروژه",
    BROWSERTASK: "استخر پروژه ها/کارها",
    CREATELISTING: "ایجاد اولین بسته پیشنهادی",
    LOOKSLIKEYOU: "هیچ کار/ پروژه تکمیل شده ای یافت نشد. برای ایجاد یک کار و دریافت پیشنهاد بر روی لینک زیر کلیک کنید.",

    LOOKSLIKEYOU_ALL: "کار/ پروژه ای یافت نشد. برای ایجاد یک کار و دریافت پیشنهاد بر روی لینک زیر کلیک کنید.",
    LOOKSLIKEYOU_POST: "کار/ پروژه ای یافت نشد. برای ایجاد یک کار و دریافت پیشنهاد بر روی لینک زیر کلیک کنید.",
    LOOKSLIKEYOU_BOOKINGREQUEST: "هیچ درخواست رزروی برای بسته های پیشنهادی شما یافت نشد. برای ایجاد یک بسته پیشنهادی بر روی لینک زیر کلیک کنید",
    LOOKSLIKEYOU_OFFERPENDING: "شما هنوز هیچ پیشنهادی ارسال نکرده اید. برای رفتن به استخر پروژه ها/کارها و ارسال پیشنهاد بر روی لینک زیر کلیک کنید.",
    LOOKSLIKEYOU_OFFERACCEPT: "شما هنوز هیچ پیشنهادی ارسال نکرده اید. برای رفتن به استخر پروژه ها/کارها و ارسال پیشنهاد بر روی لینک زیر کلیک کنید.",
    LOOKSLIKEYOU_CANCELTASK: "هیچ کار/ پروژه لغو شده ای یافت نشد. برای ایجاد یک کار و دریافت پیشنهاد بر روی لینک زیر کلیک کنید.",
    LOOKSLIKEYOU_COMPLETEDTASK: "هیچ کار/ پروژه تکمیل شده ای یافت نشد. برای ایجاد یک کار و دریافت پیشنهاد بر روی لینک زیر کلیک کنید.",

    TASKS: 'وظایف',
    BOOKING: 'رزرو',
    SELECTTASK: 'وظایف را انتخاب کنید',
    ALLTASK: 'همه کارها',
    CANCELLEDTASK: 'کار های لغو شده',
    POSTEDTASK: 'کارهای ایجاد شده',
    COMPLETEDTASK: 'کارهای تکمیل شده',
    BOOKINGREQ: 'درخواست های رزرو',
    OFFERPENDING: 'پیشنهادات در صف انتظار',
    OFFERACCEPTED: 'پیشنهادات پذیرفته شده',
    REMOTE: "کار از راه دور",
    POSTEDON: "ارسال شده در :"
  },
  BROWSE: {
    HEADERTEXT: 'استخر پروژه ها/کارها',
    NOTASK: "رکوردی مطابق با فیلتر های جستجوی شما پیدا نشد.",
    BANNERHEADING: 'کسب درآمد بیشتر با لیست',
    BANNERDESCRIPTION: 'ایجاد لیست و به خوبی ترویج خدمات خود را در EazyPay به صورت رایگان',
    LEARNMORETEXT: 'بیشتر بدانید',
    REMOTE: "کار از راه دور"
  },
  GETITDONE: {
    HEADTEXT: 'لیست کارهای خود را انجام دهید',
    TEXT: 'با چند بار کلیک در کتاب فوری ، دارای رتبه برتر شوید',
    DESCTEXT: 'درباره وظیفه بعدی رئیس خانه یا عزل کردن به ما بگویید و با یک Tasker دارای رتبه عالی که می تواند کار را انجام دهد مطابقت داشته باشید',
    CARDTEXT: 'از',
    TASKOFFER: 'آنچه را که نیاز دارید توصیف کنید و پیشنهادهایی دریافت کنید',
    RECEIVEANDREMOVE: ' دریافت و حذف پیشنهادات از Tasker که می تواند کمک کند',
    BOOKINGDESC: 'رزرو فوری محبوب',
    CLEANING: "تمیز کردن",
    FULLHOUSE: "حذف خانه های کامل",
    HANDYMAN: "کارگر دستی",
    ASSAMBLY: "مونتاژ",
    DELIVERY: "تحویل",
    GARDENING: "باغبانی",
    BUSSINESS: "کسب و کار و مدیر",
    EVENT: "رویداد و عکاسی",
    EVERYTHING: "همه چیز دیگر",
    POSTATASK: " ایجاد کار/پروژه",
    TOPOSTINGATASK: "قبل از ایجاد یک کار می بایست ابتدا ایمیل و شماره موبایل خود را تایید کنید",
    EXPLOREANDBOOK: "جستجو در استخر لیست ها و رزرو بسته های پیشنهادی",
    BROWSESERVICES: "مرور خدمات در همه دسته بندی ها",
    CANTFIND: "نمی توانید آنچه را که نیاز دارید پیدا کنید؟",
    CANTFIND2: "آیا نمی توانید آنچه را که نیاز دارید پیدا کنید؟",
    POSTATASKANDGETOFFERS: "ایجاد یک کار و دریافت پیشنهادات",
    POSTATASKANDGETOFFERS2: "ایجاد یک کار و دریافت پیشنهاد"
  },
  POSTTASK: {
    NO: "خیر",
    YES: "بله",
    // HEADERTEXT: 'ارسال پست',
    HEADERTEXT: 'کارهای ایجاد شده',
    HEADERTEXT2: "کار/پروژه خود را ارسال کنید",
    DETAILS: 'چه کار یا پروژه ای لازم است انجام شود ؟',
    WHEN: 'زمان و‌مکان کار/پروژه را انتخاب کنید',
    IMAGE: 'تصاویر',
    BUDGET: 'تعیین مبلغ',
    DESC: 'به ما بگوئید چه نیاز هایی دارید و‌چه کارهایی باید انجام شود',
    CATAGORY: 'دسته بندی اصلی را انتخاب کنید',
    SUBCATAGORY: 'یک زیر مجموعه انتخاب کنید',
    CATEGORIES: "دسته بندی ها",
    SUBCATEGORIES: "زیر مجموعه ها",
    WHATDONE: 'چه کاری لازم است انجام شود؟',
    DETAIL: 'جزئیات چیست',
    PLACETEXT1: 'به عنوان مثال: به حرکت مبل من کمک کنید...',
    PLACETEXT2: 'لطفا اطلاعات تماس خود را به اشتراک نگذارید، در صورت مشاهده، پروفایل کاربر مورد نظر بلاک شده و حق هرگونه اعتراضی را از خود سلب خواهد نمود.',
    ADDMUSTHAVES: "باید ها و‌ضروریات را وارد کنید ",
    MUSTHAVES: "باید ها و ضروریات",
    MUSTHAVESHEADING: "حداکثر سه موردی که تمایل دارید مجری/ پیمانکار مورد نظر داشته باشد، مانند:",
    WHATMUST: "چه چیزی باید داشته باشند یا انجام دهند",
    ADD: "اضافه کردن",
    SAVE: "ذخیره",
    NEXT: 'بعدی',
    SUBMIT: 'وظیفه خود را ارائه دهید',
    WHENDONE: 'تاریخ انجام کار/پروژه خود را مشخص نمایید',
    ADDYOURTASKIMAGE: 'میتوانید تصاویری برای کار/پروژه خود انتخاب نمایید',
    SUBTITLETASKIMAGE: 'هر چقدر تصاویر اضافه شده با کار/پروژه شما مطابقت داشته باشند، شانس پیدا کردن مجریان/پیمانکاران مناسب را برای شما افزایش میدهند',
    TIME: 'اگر نیاز دارید که کار/پروژه شما در ساعت/زمان مشخصی انجام گردد، لطفا ساعت دقیق را مشخص نمایید.',
    LOCATION: 'محل',
    ENTERYOURLOCATION: 'محل انجام کار/پروژه خود را مشخص نمایید',
    WHATISYOURBUDGET: 'تعیین مبلغ پروژه',
    WHEREDOYOUNEED: 'این کار/پروژه به چه شکل می بایست انجام شود؟',
    SUBTITLEYOURBUDGET: 'مبلغ پروژه را میتوانید به صورت کلی و یا ساعتی مشخص نمایید. توجه داشته باشید این مبلغ بعد از ایجاد کار/پروژه نیز قابل تغییر می باشد.',
    ONLINE: 'دور کاری',
    INPERSON: 'حضوری',
    TOTAL: 'کل',
    HOUR: 'نرخ ساعتی ',
    ENTER: 'اینجا وارد کنید…',
    TBUDGET: 'مبلغ پروژه',
    DESCRIPTION25CHAR: "لطفا حداقل ۲۵ کاراکتر توضیحات را وارد کنید",
    ENTERDESCRIPTION: "توضیحات را وارد کنید",
    TITLE10CHAR: "لطفا عنوان حداقل ۱۰ کاراکتر را وارد کنید",
    ENTERTITLE: "عنوان را وارد کنید",
    ENTERSUBCATAGORY: "زیر مجموعه را وارد کنید",
    ENTERCATAGORY: "دسته را وارد کنید",
    ATFIRSTENTER: 'در ابتدا چیزی را وارد کنید',
    PRESSADD: "دکمه افزودن را فشار دهید تا وظیفه خود ذخیره شود",
    SELECTDATE: "تاریخ را انتخاب کنید",
    CHOOSEANYDATETYPE: "هر نوع تاریخ را انتخاب کنید",
    SELECTLOCATION: "مکان را انتخاب کنید",
    ENTEREACHFIELD: "لطفا هر فیلد را وارد کنید",
    ENTER10Char: "لطفا حداقل وارد کنید ۱۰ حروف.",
    ENTER25Char: "لطفا حداقل وارد کنید ۲۵ حروف.",
    ENTERVALUE500000000: "لطفاً مقداری کمتر یا مساوی وارد کنید ۵۰,۰۰۰,۰۰۰.",
    ENTERVALUE500000000HOURLYRATE: "لطفاً مقداری کمتر یا مساوی وارد کنید ۵۰,۰۰۰,۰۰۰.",
    ENTERVALUE100000000NUMOFHOUR: "لطفاً مقداری کمتر یا مساوی وارد کنید ۱۰,۰۰۰,۰۰۰.",
    HRS: "ساعت",
    ONDATE: "در تاریخ",
    ON: "در",
    BEFOREDATE: "قبل از تاریخ",
    BEFORE: 'قبل از',
    IMFLEXIBLE: "من انعطاف پذیرم",
    ENTERTIME: "ساعت /زمان مورد نظر را انتخاب نمایید",
    SEARCH: "جستجو",
    OPTIONAL: "(اختیاری)",
    ENTERIMAGEIN_JPEGPNGJPG: "تصاویر باید یک فایل از نوع: jpeg، png، jpg باشند",
    NUMBEROFHOURS: "تعداد ساعت",
    SUPPORTRDFIELS: "فایل های پشتیبانی شده: jpg، .jpeg، .png",
    MAXFILESIZE: "حداکثر حجم فایل: ۱۰ مگابایت",
    ENTERVALUEMORETHAN1000: "لطفاً مقداری بزرگتر یا مساوی وارد کنید ۱۰۰۰.",
    ENTERVALUEMORETHAN1000HOURLYRATE: "لطفا مقداری بزرگتر یا مساوی ۱۰۰۰ تومان وارد کنید",
    LASTDIGITMUSTBE0: "آخرین رقم باید ۰ باشد",
    SELECTMUCHMORETIME: "زمان بسیار بیشتری را از زمان فعلی انتخاب کنید",
    DONTSPACIALCHAR: "همه فیلدها باید یک عدد صحیح وارد کنید. از کاراکترها و فضاهای خاص استفاده نکنید",

    // *************************edittask********************

    EDITTASK: "ویرایش وظیفه",
    SIMILARTASK: "کار مشابه را پست کنید",
    EDIT: "ویرایش",
    CANCEL: "لغو",
    POSTSIMILARTASK: "ایجاد و ارسال یک کار مشابه",
    REPORTHISTASK: "گزارش خطا",
    READMORE: "ادامه مطلب +",
    READLESS: "بستن -",
    MUSTHAVESTITLE: "باید ها و ضروریات",
    CANCELTASK: "لغو کار",
    AREYOUSURE: "آیا مطمئن هستید؟",
    CANCELABUTTON: "لغو",
    OK: "باشه",
    DELETETASKIMAGE: "تصویر با موفقیت حذف شد"
  },
  BROWSEFILTER: {
    HEADERTEXT: "فیلترها",
    LOCATION: 'محل',
    LOCATIONPLACEHOLDER: 'محل را انتخاب کنید',
    DISTANCE: 'مسافت',
    CATEGORY: 'دسته بندی',
    CATEGORYPLACEHOLDER: 'یک گزینه انتخاب کنید',
    SELECT: 'انتخاب کنید',
    TOBEDONE: 'که باید انجام شود',
    INPERSON: 'حضوری',
    REMOTELY: 'از راه دور',
    ALL: 'همه',
    RANGE: 'محدوده بودجه',
    DATE: 'تاریخ',
    DATEPLACEHOLDER: 'تاریخ را انتخاب کنید',
    APPLY: 'درخواست دادن',
    RESET: 'تنظیم مجدد',
    KM: 'کیلومتر',
    RIYALS: 'ریال',
    AND: '&',
    KEYWORDS: 'کليدواژه',
    SUBCATEGORY: "زیرمجموعه",
    CHOOSECATEGORY: "دسته بندی اصلی",
    SORTBY: "مرتب سازی بر اساس",
    BYDATE: "بر اساس تاریخ",
    PRICELOWTOHIGH: "ق قیمت پایین به بالا",
    PRICEHIGHTOLOW: "قیمت بالا به پایین",
    FROM: "از",
    TO: "به",
    ATFIRSTSELECTCATAGORY: "ابتدا دسته را انتخاب کنید",
    TASKFOUND: "وظایف پیدا شد",
    SELECTSUBCATEGORYALSO: "زیر شاخه را نیز انتخاب کنید",
    EARN: "مبلغ",
    DUEDATE: "سررسید :",
    POSTEDBY: "ارسال شده توسط",
    VIEWTASK: "مشاهده کار",
    IRR: "ریال",
    TOMAN: "تومان",


    DRAFT: "پیش نویس",
    OPEN: "فعال",
    ASSIGNED: "محول شده",
    COMPLETED: "تکمیل شده",
    CANCELLED: "لغو شده",

    BUDGETRANGE: "تعیین مبلغ"

  },
  LOGINSCREEN: {
    HEADERTEXT: "ورود",
    EMAILPLACEHOLDER: 'پست الکترونیکی / شماره تلفن',
    PASSWORDPLACEHOLDER: 'کلمه عبور',
    FORGOTPASSBTN: 'رمز عبور خود را فراموش کرده اید ؟',
    LOGIN: 'ورود',
    SEPERATOR: 'یا ادامه دهید',
    FACEBOOK: 'فیس بوک',
    GOOGLE: 'گوگل',
    SIGNUPTEXT: 'حساب کاربری ندارید',
    SIGNUPBTN: 'ثبت نام',
    LOGOUT: "خروج با موفقیت انجام شد"
  },
  FORGOTPASSBTN: {
    BACKTO: "بازگشت به صفحه ورود",
    RESETPASSWORD: "تغییر رمز عبور",
    RESETPASSWORD2: "رمز عبور خود را بازیابی کنید",
    ENTERYOUREMAIL: "رمز عبور خود را فراموش کرده اید ؟",
  },
  SIGNUPCREEN: {
    HEADERTEXT: 'ثبت نام',
    NAMEPLAACEHOLDER: 'نام',
    LASTNAMEPLAACEHOLDER: 'نام خانوادگی',
    EMAILPLACEHOLDER: 'آدرس ایمیل',
    MOBILEPLACEHOLDER: 'شماره تلفن',
    PASSWORDPLACEHOLDER: 'کلمه عبور',
    CONFPASSPLACEHOLDER: 'تکرار رمز عبور',
    FORGOTPASSBTN: 'رمز عبور را فراموش کرده اید',
    SIGNUP: 'ثبت نام',
    SEPERATOR: 'یا با آن ثبت نام کنید',
    FACEBOOK: 'فیس بوک',
    GOOGLE: 'گوگل',
    SIGNUPTEXT: 'حساب ندارید؟',
    SIGNUPBTN: 'ثبت نام',
    DESCTEXT: 'با کلیک بر روی ثبت نام موافقت خود را با قوانین ایران تسکر اعلام میدارم ',
    AND: 'و',
    PRIVACY: 'حریم خصوصی',
    TERMS: 'شرایط و قوانین',
  },
  BASICINFO: {
    HEADERTEXT: 'ویرایش پروفایل',
    HEADING1: 'اطلاعات پایه',
    PLACEHOLDER: 'اینجا وارد کنید',
    ABOUTMEPLACEHOLDER: 'توجه داشته باشید به هیچ عنوان اطلاعات تماس خود اعم از شماره تماس ، ایمیل و غیره را وارد نکنید ، در صورت مشاهده پروفایل مورد نظر بلاک خواهد شد',
    FIRSTNAME: 'نام',
    LASTNAME: 'نام خانوادگی',
    TAGLINE: 'عنوان پروفایل',
    EMAIL: 'پست الکترونیک',
    PHONENUMBER: 'شماره تلفن',
    HOURLYRATING: 'نرخ ساعتی (به عنوان پیمانکار)',
    HIGHESTQUAL: 'بالاترین مدرک تحصیلی',
    WORKEXP: 'تجربه کاری (به سال)',
    LANGUAGEKNOWN: 'زبان هایی که می توانید صحبت کنید',
    SELECTLANGUAGE: 'زبان ها را انتخاب کنید',
    TAXID: 'کد مالیاتی',
    DOB: 'تاریخ تولد',
    ROLEHEADING: 'من میخواهم در ایران تسکر',
    POSTTASKS: 'ایجاد کار و اشتغال زائی',
    EARNMONEY: 'کسب درآمد',
    VEICHLEHEADING: 'چگونه رفت و آمد می کنید؟',
    BICYCLE: 'دوچرخه',
    CAR: 'ماشین',
    ONLINE: 'آنلاین',
    SCOOTER: 'اسکوتر',
    TRUCK: 'کامیون',
    WALK: 'پیاده',
    HEADING2: 'آدرس پستی',
    COUNTRY: 'کشور',
    STATE: 'دولت',
    CITY: 'شهر',
    LOCATION: "محل",
    ABOUTME: 'درمورد من',
    PROFILEIMAGE: 'بارگذاری تصویر پروفایل',
    BACKMAGE: 'بارگذاری تصویر پس زمینه',
    SAVE: 'ذخیره و ادامه دهید',
    VERIFIED: 'تأیید شده',
    VERIFY: 'تأیید',
    NOTIFICATION: "اطلاع",
    ON: "بر",
    OFF: "خاموش"
  },
  PORTFOLIO: {
    HEADERTEXT: 'ویرایش پروفایل',
    HEADING: 'تصاویر نمونه کارها (اختیاری)',
    PORTFOLIODELETE: 'نمونه کارها با موفقیت حذف شد',
    DESC: 'برای نمایش بخش نمونه کارها خود ، حداکثر ۱۵ تصویر را انتخاب کنید',
    PREVIMAGES: 'تصاویر انتخاب شده قبلی',
    RECENTIMAGES: 'تصاویر انتخابی اخیر',
    BTNTEXT1: 'سایز پیشنهادی ۱۸۰px * ۲۴۰px',
    BTNTEXT2: 'پرونده های پشتیبانی شده: .jpg، .jpeg، .png. حداکثر حجم هر پرونده: ۱۰ مگابایت',
    SAVE: 'همه تغییرات را ذخیره کنید',
  },
  SKILLS: {
    HEADERTEXT: 'مهارت ها',
    INPUTHEADING: 'در چه کار هایی خوب هستید',
    INPUTSUBHEADING: 'در این قسمت مهارت های خود را وارد کنید. همچنین هر زمان که مهارت جدیدی کسب کردید، این قسمت را به روز رسانی کنید. این شانس شما را در رقابت با دیگران افزایش خواهد داد.',
    PLACEHOLDER: 'اینجا وارد کنید',
    ADDBTN: '+ اضافه کردن',
    PREVSKILL: "مهارتی که قبلاً اضافه شده است",
    RECENTSKILL: "مهارتی که اخیراً اضافه شده است",
    ADDEDSKILLHEADING: 'مهارت های من',
    SKILLDELETE: "مهارت با موفقیت حذف شد",
    SAVE: 'ذخیره / ادامه',
    ADDATLEASTONESKILL: 'لطفا حداقل یک مهارت اضافه کنید',
    ENTERSOMESKILL: 'یک مهارت وارد کنید',
    SKILLPLACEHOLDER: "به عنوان مثال کابینت ساز...",
  },
  DASHBOARD: {
    TIER: "ردیف",
    HEADERTEXT: 'داشبورد من',
    CARDHEADING: 'ردیف برنز',
    CARDTEXT1: '۲۰% هزینه خدمات بدون GST',
    CARDTEXT1A: "هزینه خدمات",
    CARDTEXT2: 'بر اساس رتبه فعلی شما',
    SCOREHEADING: 'رتبه شما',
    COMPLETIONRATING: 'رتبه تکمیل',
    COMPLETIONDESC:
      'ما رتبه بندی تکمیل شما را عالی کرده ایم تا به شما در شروع سفر ایران تاسکر کمک کند. وظیفه محوله خود را کامل نگه دارید تا این نمره بالا بماند.',
    EARNING: 'درآمد شما',
    EARNINGDESC: '۰ ریال در ۳-۰ روز گذشته',
    EARNINGDESC1: 'در آخر',
    EARNINGDESC2: 'روزها',
    RIYALS: 'ریال',
    QUESTEXT: 'رتبه ها و طبقات چگونه کار می کنند؟',
    BENEFITHEADING: 'مزایای طبقه بعد…',
    BENEFITTEXT1: 'رسیدن به طبقه نقره برای هزینه خدمات کمتر',
    BENEFITTEXT2: 'پرداخت هزینه کمتر با هزینه خدمات ۱۶.۴',
    BENEFITTEXT2A: 'پرداخت کمتر با هزینه خدمات ',
    LAST: "آخر",
    TASK: "وظایف",
    DAYS: "روزها",
    POOR: "ضعیف",
    OKAY: "مقبول",
    GOOD: "خوب",
    EXCELLENT: "عالی",
    TIERDETAILS: "جزئیات ردیف"
  },
  PAYMENTMETHOD: {
    HEADERTEXT: 'روش پرداخت'
  },
  CHANGEPASS: {
    HEADERTEXT: 'رمز عبور را تغییر دهید',
    OLDPASSWORD: 'رمز عبور فعلی',
    NEWPASSWORD: 'رمز عبور جدید',
    CONFIRMNEWPASSWORD: 'رمز عبور خود را تایید کنید',
    CONFIRMNEWPASSWORD2: 'تکرار رمز عبور',
    UPDATEPASSWORD: "به روز رسانی رمز عبور",
    ENTERHERE: "اینجا وارد کنید"
  },
  MYPROFILE: {
    TAB1: 'به عنوان مجری',
    TAB2: "به عنوان کارفرما",
    NOREVIEWTEXT: 'هنوز نظری دریافت نشده است',
    ABOUT: 'عنوان شغلی:',
    MEMBERSINCE: 'عضو از',
    BADGES: 'نشان ها',
    PORTFOLIO: 'نمونه کار ها',
    SKILLS: 'مهارت ها',
    NOSKILL: 'کاربر هنوز هیچ مهارتی را اضافه نکرده است.',
    NOLISTING: "بسته پیشنهادی یافت نشد",
    NOTRANSPOTATION: "هیچ متد رفت و آمدی اضافه نشده است",
    NOLANGUAGES: "هیچ زبانی اضافه نشده است",
    NOREVIEWSASAPOSTER: "این کاربر هنوز هیچ دیدگاهی به عنوان کارفرما کسب نکرده است",
    NOREVIEWSASATASKER: "این کاربر هنوز هیچ دیدگاهی به عنوان مجری/پیمانکار کسب نکرده است",
    // REVIEWS: 'مرور',
    LANGUAGE: 'زبان ها',
    GETAROUNDBY: "حمل و نقل",
    ONLINE: 'دور کاری',
    LISTING: "بسته های پیشنهادی",
    NOREVIEWFOUND: "این کاربر هنوز هیچ دیدگاهی به عنوان مجری/پیمانکار کسب نکرده است",
    NOREVIEWFOUND2: "هیچ بررسی در دسترس نیست",
    COMPLETEDTASKS: "کار/پروژه های تکمیل شده",
    STARS: "ستاره",
    REVIEWS: "دیدگاه",
    FROM: "از"
  },
  ERROR: {
    REFRESHING: "تازه کردن...",
    ENTERFNAME: "نام را وارد کنید",
    ENTERLNAME: "نام خانوادگی را وارد کنید",
    ENTERTAGLINE: "خط تگ را وارد کنید",
    ENTEREMAIL: "ایمیل را وارد کنید",
    ENTEREMAILORPHONE: "ایمیل یا شماره تلفن را وارد کنید",
    ENTERVALIDEMAIL: "ایمیل معتبر وارد کنید",
    ENTERPHONE: "حداقل ۸ تا ۱۲ رقم شماره تلفن معتبر وارد کنید",
    ENTERHOURLYRATE: "نرخ ساعتی را وارد کنید",
    SELECTCOUNTRY: "کشور را انتخاب کنید",
    ENTERSTATENAME: "نام ایالت را وارد کنید",
    ENTERCITYNAME: "نام شهر را انتخاب کنید",
    SELECTLOCATION: "مکان را انتخاب کنید",
    ENTEREXPERIENCE: "تجربه را در تعداد سال وارد کنید",
    ENTERHEIGHTESTQUALIFICATION: "بالاترین مدرک تحصیلی خود را وارد کنید",
    ENTERDOB: "تاریخ تولد را وارد کنید",
    SELECTGETAROUND: "نحوه برخورد خود را انتخاب کنید",
    SELECTLANGUAGE: "زبان را انتخاب کنید",
    SOMETHINGERRORINAPI: "خطایی در تماس api وجود دارد",
    AGEVALIDATION: "برای استفاده از EazyPay باید ۱۸ سال یا بیشتر داشته باشید",
    EXPERIENCEPOSITIVEVALUE: "تجربه را با ارزش مثبت وارد کنید",
    HOURLYRATEPOSITIVEVALUE: "نرخ ساعتی را با مقدار مثبت وارد کنید",
    ENTERVALIDPHONE: "شماره تلفن معتبر وارد کنید",
    ENTERPASSWORD8DIGIT: "حداقل ۸ کاراکتر وارد کنید",
    ENTERPASSWORD: "لطفا رمز عبور را وارد کنید",
    CONFIRMPASSWORD: "مجددا رمز عبور خود را وارد کنید",
    SUCCESSFULLYLOGIN: "شما با موفقیت وارد سیستم شده اید",
    SUCCESSFULLYREGISTER: "شما با موفقیت ثبت نام کردید",
    LOGINCANCEL: "ورود لغو شد",
    BOTHEMAIL_PHONE: "ایمیل و تلفن هر دو قبلاً گرفته شده است",
    FILLUPALLFIELD: "لطفاً همه فیلدها را پر کنید",
    PASSWORDCHANGESUCCESSFULLY: "رمز عبور با موفقیت تغییر کرد",
    ENTERSAMEPASSWORD: "همان رمز عبور را وارد کنید",
    ENTERYOUESKILL: "مهارت خود را وارد کنید",
    ENTERADDBUTTON: "برای افزودن مهارت های خود دکمه افزودن را وارد کنید",
    ENTERIMAGEIN_JPEGPNGJPG: "تصاویر نمونه کارها باید یک فایل از نوع باشند: jpeg ، png ، jpg",
    // make an offer
    SUCCESSFULLYTASKASSIGNED: "وظیفه با موفقیت محول شد",
    PAYMENTCANCEL: "لغو پرداخت",
    WAIT: "صبر کن",
    ATFIRSTENTERMSG: "ابتدا پیام را وارد کنید",
    ENTERMAX1000MSG: "حداکثر ۱۰۰۰ کاراکتر پیام را وارد کنید",
    MSGSEND: "ارسال پیام",
    PRICEINCREASESUCESSFULLY: "افزایش قیمت با موفقیت",
    ENTERREASON: "دلیل را وارد کنید",
    ACCOUNTVERIFYING: "تایید حساب......",
    ATFIRSTPHEMAILVERIFIED: "ابتدا شماره تلفن و ایمیل خود را تأیید کرد",
    PLEASESELECTADATE: "لطفا تاریخ را انتخاب کنید",
    YOUCANSENDWITHDRAW: "شما می توانید درخواست برداشت را پس از فاصله ۲ روزه درخواست برداشت قبلی خود ارسال کنید",
    YOUCANSENDWITHDRAW2: "توجه : درخواست برداشت از کیف پول به فاصله ۲ روز از آخرین برداشت مجاز می باشد.",
    DAYSLEFT: "روزهای باقی مانده",
  },
  TABNAVIGATION: {
    GETITDONE: "انجامش بده",
    MYTASK: "وظایف من",
    BROWSER: "مرورگر",
    MESSAGE: "پیام ها",
    MORE: "بیشتر",
    NOTIFICATIONS: 'اعلان ها'
  },
  HELP: {
    HEADER: 'مرکز راهنمایی ایران تاسکر',
    SEARCHRESULT: "نتایج جستجو",
    KNOWLEDGEBASE: "پایگاه دانش",
    SEARCH: "جستجو کردن",
    NORESULTFOR: "هیچ نتیجه ای برای",
    BROWSEKNOWLEDGEBASE: "جستجوی مجدد",
  },
  DISPUTE: {
    ACTIVE: 'فعال',
    CLOSED: 'بسته شده',
    NODISPUTE: 'اختلافی پیدا نشد',
    FINALEVIDENCE: '(مدارک و مستندات نهایی)',
    CLICKTOSELECTFILES: 'برای انتخاب فایل ها کلیک کنید',
  },
  LMS: {
    HEADER: "فهرست خود را ایجاد کنید",
    CATEGORY: "دسته بندی",
    DESCRIPTION: "شرح",
    PRICINGANDPACKAGING: "قیمت گذاری بسته های پیشنهادی",
    LOCATION: "محل",
    AVAILABILITY: "زمان در دسترس بودن",
    IMAGES: "تصاویر",
    BOOKINGMESSAGE: "پیغام رزرو",
    ONLINESERVICE: "دور کاری آنلاین",

    LMS1_TEXT_1: "این بسته پیشنهادی چه نوع خدماتی را ارائه می دهد؟",
    LMS1_TEXT_2: "دسته بندی را انتخاب کنید که با خدمات ارائه شده در بسته پیشنهادی شما مطابقت داشته باشد.این به مشتریان کمک می کند تا بسته پیشنهادی شما را راحت تر پیدا کرده و رزرو کنند.",
    LMS1_TOAST_1: "دسته را انتخاب کنید",
    LMS1_TOAST_2: "زیرمجموعه را انتخاب کنید",


    CHOOSECATEGORYTITLE: "دسته بندی خدمات اصلی را انتخاب کنید",
    CHOOSECATEGORYPLACEHOLDER: "دسته بندی خدمات اصلی را انتخاب کنید",
    CHOOSESUBCATEGORYTITLE: "یک زیر مجموعه برای دسته بندی خدمات خودتان انتخاب کنید",
    CHOOSESUBCATEGORYPLACEHOLDER: "یک زیر مجموعه برای دسته بندی خدمات خودتان انتخاب کنید",





    LMS2_TEXT_1: "بسته پیشنهادی خود را توصیف کنید",
    LMS2_TEXT_2: "این فرصت در اختیار شما است تا مشتریان بالقوه را تحت تأثیر آنچه این بسته پیشنهادی ارائه می دهد قرار دهید و اینکه چرا شما بهترین فرد برای انجام این کار هستید",
    LMS2_TEXT_3: "عنوان",
    LMS2_TEXT_4: "یک عنوان کوتاه بنویسید که دقیقاً خدماتی را که ارائه می دهید توصیف کند",
    LMS2_TEXT_5: "به عنوان مثال ، عکاسی از نوزاد تازه متولد شده",
    LMS2_TEXT_6: "جستجوی برچسب ها",
    LMS2_TEXT_7: "حداکثر ۱۵ برچسب جستجو را که مشتریان ممکن است هنگام جستجوی بسته پیشنهادی شما استفاده کنند ،تایپ و وارد کنید",
    LMS2_TEXT_8: "به عنوان مثال، این سرویس از ۸ صبح تا ۵ بعداظهر قابل ارائه می باشد.",
    LMS2_TEXT_9: "ویرایش کنید",
    LMS2_TEXT_10: "شرح",
    LMS2_TEXT_11: "لطفاً خدماتی را که ارائه می دهید با جزئیات بیشتر توضیح دهید",
    LMS2_TEXT_12: "توضیحات خود را اینجا وارد کنید ...",
    LMS2_TEXT_13: "لطفا توجه داشته باشید",
    LMS2_TEXT_14: "قیمت ها را در توضیحات بسته پیشنهادی خود قرار ندهید. در مرحله بعدی می توانید بسته های قیمتی را برای بسته های پیشنهادی خود مشخص کنید.",
    SEARCHTAGCANNOTBE15: "برچسب های جستجو نمی توانند بیشتر از ۱۵ باشند",
    ATLEAST50CHAR: "لطفا حداقل ۵۰ کاراکتر توضیحات را وارد کنید",
    ATLEAST1TAG: "لطفاً حداقل ۱ برچسب (های) ارائه دهید",
    PLEASEENTERTITLE: "لطفا عنوان را وارد کنید",
    ENTERATAG: "یک برچسب جستجو را وارد کنید",
    TAGDELETED: "برچسب جستجو با موفقیت حذف شد",

    PRICEANDPACKAGEYOURLISTING: "قیمت بسته های پیشنهادی",
    PRICEYOURLISTINGWITH: "می توانید از ۱ تا ۵ بسته قیمتی ایجاد کنید",
    PACKAGE1: "بسته ۱",
    PACKAGE22: "بسته ۲",
    PACKAGE3: "بسته ۳",
    PACKAGE4: "بسته ۴",
    PACKAGE5: "بسته ۵",
    OPTIONAL: "(اختیاری)",
    CUSTOMERWILLSELECT: "مشتریان در هنگام رزرو بسته پیشنهادی شما فقط می توانند یکی از بسته های قیمتی را انتخاب نمایند",
    ADD: "اضافه کردن",
    PACKAGENAME: "نام بسته",
    DESCRIBETHISPACKAGE: "در ارتباط با این بسته پیشنهادی توضیح دهید",
    LISTEVERYTHING: "همه چیزهایی را که این بسته‌ پیشنهادی شامل می شود لیست کنید",
    ENTERHERE: "اینجا وارد کنید...",
    TOTALPRICE: "قیمت کل",
    BELOWTOTALPRICE_TEXT: "ایران تسکر هزینه خدمات را بر اساس رتبه بندی و‌طبقه شما در سایت کسر خواهد کرد، برای اطلاعات بیشتر کلیک کنید.. ",
    PLEASEADD5CHARNAME: "لطفا حداقل ۵ کاراکتر نام بسته اضافه کنید",
    PLEASEADD25CHARDESCRIPTION: "لطفا حداقل ۲۵ کاراکتر توضیحات بسته اضافه کنید",
    PLEASEENTERAMOUNT1000TOMAN: "لطفا مبلغ حداقل ۱۰۰۰ تومان تا ۵۰۰۰۰۰۰۰ تومان وارد کنید",
    PLEASEENTERALLVALUEIN2: "لطفا تمام مقادیر را در بسته وارد کنید ۲",
    PLEASEENTERALLVALUEIN3: "لطفا تمام مقادیر را در بسته وارد کنید ۳",
    PLEASEENTERALLVALUEIN4: "لطفا تمام مقادیر را در بسته وارد کنید ۴",
    PLEASEENTERALLVALUEIN5: "لطفا تمام مقادیر را در بسته وارد کنید ۵",
    PLEASEADDATLEAST1PACKAGE: "لطفا حداقل ۱ بسته قیمت اضافه کنید",

    CHOOSEWHEREYOUWILL: "محل ارائه این سرویس را انتخاب کنید",
    ONLINE: 'دور کاری',
    THISSERVICEANYWHERE: "این سرویس به صورت دورکاری نیز قابل ارائه می باشد",
    INPERSON: "در محل",
    THISSERVICEINPERSON: "این سرویس به صورت حضوری و در محل ارائه می گردد",
    IWILLSERVE: "این سرویس تا مرز",
    KM: "کیلومتر",
    FROMMYLOCATION: "از موقعیت مکانی زیر قابل ارائه می باشد",
    SELECT: "انتخاب کنید...",
    SELECTLOCATION: "لطفا مکان را انتخاب کنید",

    SETAVAILABILITY: "زمان در دسترس بودن خود را مشخص کنید",
    LETCUSTOMERSKNOW: "به مشتریان خود اطلاع دهید برنامه زمانی شما چگونه است و چه زمان هایی برای ارائه این خدمات در دسترس هستید",
    MYAVAILABILITY: "زمان های در دسترس بودن من",
    IAMAVAILABLEON: "زمان های دسترسی",
    CUSTOMERWILLREQUESTTOBOOK: "مشتریان خدمات شما را رزرو خواهند کرد. درخواست های جدید رزرو به شما اطلاع داده می شود و فرصتی برای تایید یا رد درخواست به شما داده خواهد شد.",
    YOUCANASK: "قبل از تصمیم گیری می توانید سوالات خود را مطرح کرده و الزامات را با مشتریان در میان بگذارید.",
    ENTER20CHAR: "لطفا حداقل ۲۰ کاراکتر وارد کنید",

    ADDIMAGES: 'اضافه کردن تصاویر',
    ADDHIGHQUALITYIMAGES: "تصاویری با کیفیت بالا اضافه کنید که به صورت بصری خدمات شما را توصیف کنند",
    MAINIMAGE: "تصویر اصلی",
    THISISFIRSTIMAGE: "این اولین تصویری است که مشتریان بالقوه هنگام مشاهده بسته پیشنهادی شما مشاهده می کنند",
    GALLARYIMAGES: "تصاویر گالری",
    CHOOSEUPTO15: "حداکثر ۱۵ تصویر برای نمایش کار و مهارت خود انتخاب کنید",
    MAINIMAGEMUST: "تصویر اصلی باید انتخاب شود",
    CHOOSEUPTO15IMAGES: "حداکثر ۱۵ تصویر گالری را انتخاب کنید",

    AUTOSENDAMESSAGE: "ارسال خودکار پیام به مشتریان",
    WRITEAMESSAGETOBE: "پیامی بنویسید که به طور خودکار هنگام رزرو بسته های پیشنهادی به مشتریان ارسال شود",
    WRITEAMESSAGE: "نوشتن پیام",
    THANKSFORBOOKINGMYLISTING: "از اعتماد شما برای رزرو این بسته پیشنهادی سپاسگذاریم",
    POSTYOURLISTING: "بسته پیشنهادی خود را ارسال کنید",

    MYSERVICES: "بسته های پیشنهادی من",
    CREATENEWLISTING: "ایجاد بسته جدید",
    PUBLISHED: "منتشر شده",
    PAUSED: "متوقف شده",
    NEXTSTEPS: "گام های بعدی",
    BOOKINGFORYOUR: `رزروهای بسته های پیشنهادی شما به صورت "یک کار/پروژه واگذار شده" در قسمت کارها/پروژه های شما ظاهر می شوند`,
    MYTASK: "وظیفه من",
    ABOUTLISTINGOR: "درباره لیست ها یا از ما دیدن کنید",
    HELPCENTER: "راهنمای مرکزی",
    HELPCENTER_2: "مرکز کمک",
    LISTINGDETAILS: "جزئیات لیست",
    STARTINGFROM: "شروع از :",
    ABOUTTHISTASKER: "درباره این مجری/پیمانکار",
    VIEWALLPACKAGE: "مشاهده همه بسته ها",
    PRICEPACKAGES: "قیمت بسته ها",
    COST: "هزینه :",
    CONTINUETOBOOK: "به رزرو ادامه دهید",
    REVIEWFORTHISTASKER: "دیدگاه های ثبت شده برای این مجری/پیمانکار",
    HASNOTRECIVEDANYREVIEW: "هنوز هیچ نظر/دیدگاهی دریافت نکرده است",
    REQUESTBOOKING: "درخواست رزرو",
    PLEASEFILLINTHE: "لطفاً برای ادامه رزرو خدمات فیلدهای زیر را پر کنید",
    PACKAGE: "پکیج:",
    PACKAGE2: "بسته :",
    WHEREDOYOU: "کجا باید این کار انجام شود؟",
    WHENDOYOU: "تاریخ انجام کار/پروژه خود را مشخص نمایید",
    TIMEOPTIONAL: "زمان (اختیاری)",
    WHATTIMESDO: "اگر نیاز دارید که کار/پروژه شما در ساعت/زمان مشخصی انجام گردد، لطفا ساعت دقیق را مشخص نمایید.",
    PRIVATEMSG: "پیام خصوصی (اختیاری)",
    INTRODUCEYOURSELF: "خودتان را معرفی کنید ،میتوانید جزئیات بیشتری اضافه کنید و یا اگر سوالی دارید بپرسید.",
    ENTERYOURMESSAGE: "پیام خود را اینجا وارد کنید.....",
    SENDBOOKING: "درخواست رزرو",
    VIEWBOOKINGREQUEST: "مشاهده درخواست های رزرو",
    WHATHAPPENS: "مرحله بعدی چیست؟",
    CREATELISTING: "ایجاد فهرست",
    WORKLESSEARNMORE: "کمتر کار کنید و بیشتر بدست بیاورید",
    BEONEOFTHE: "اولین کسی باشید که خدمات خود را بصورت بسته های پیشنهادی ارائه می کند. ما خدمات شما را بصورت رایگان نمایش خواهیم داد.",
    CREATEMYFIRST: "اولین بسته پیشنهادی من را ایجاد کن",
    BELLOWFSTBUTTON: "شما می توانید از هر مهارتی کسب درآمد کنید، این ویژگی کاملا رایگان است و راه اندازی آن کمتر از ۱۰ دقیقه طول می کشد.",
    CREATEYOURFIRST: "اولین بسته پیشنهادی من را ایجاد کن",
    YOUCANEARN: "از هر مهارتی می توانید درآمد کسب کنید",
    THEREISNOLIMIT: "محدودیتی برای ایجاد بسته های پیشنهادی وجود ندارد",
    WEAREHERETOHELP: "ما اینجا هستیم تا به شما کمک کنیم",
  },
  TELLAFEIRND: {
    FRIENDNAME: "نام و نام خانوادگی",
    FRIENDEMAIL: "ایمیل دوست",
    ENTERYOURFRIENDNAME: "نام دوست خود را وارد کنید",
    ENTERYOURFRIENDEMAIL: "ایمیل دوست خود را وارد کنید",
    MESSAGE: "پیام",
    PLEASEWRITEACOMMON: "لطفا یک پیام مشترک برای همه دوستان خود بنویسید.",
    ENTERYOURMESSAGEHERE: "پیام خود را اینجا وارد کنید...",
    FRIEND: "دوست",
    NAME: "نام :",
    EMAIL: "پست الکترونیک :",
    ENTERMESSAGE: "پیام را وارد کنید",
    ENTERATLEAST1FRIEND: "حداقل ۱ دوست وارد کنید",
    ENTERADDBUTTON: "ابتدا دکمه اضافه کردن را وارد کنید تا نام و ایمیل ذخیره شود",
    ENTERNAME: "نام را وارد کنید"
  },
  NOTIFICATIONS: {
    HEADER: "اعلان"
  },
  WITHDRAW: {
    NORECORDFOUND: "رکوردی پیدا نشد"
  },
};
